import { SymbolView } from 'expo-symbols';
import { useRouter } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { borderRadii, borderWidths, spacing, typography } from '@/constants/theme';
import { categoryIconCatalog, categoryIconGroupNames, fallbackCategoryIcon, isCategoryIcon, searchCategoryIcons, type CategoryIcon } from '../category-icons';
import { CategoryValidationError } from '../category.service';
import { categoryService } from '../categories';
import type { CategoryType, CategoryValidationErrors } from '../category.types';
import { useAppTheme } from '@/hooks/use-app-theme';

export function CategoryForm({ categoryId, initialType = 'expense' }: { categoryId?: string; initialType?: CategoryType }) {
  const router = useRouter(); const insets = useSafeAreaInsets(); const theme = useAppTheme();
  const [name, setName] = useState(''); const [type, setType] = useState<CategoryType>(initialType); const [icon, setIcon] = useState<CategoryIcon>('other');
  const [iconSearch, setIconSearch] = useState('');
  const [errors, setErrors] = useState<CategoryValidationErrors>({}); const [generalError, setGeneralError] = useState<string>();
  const [loading, setLoading] = useState(Boolean(categoryId)); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!categoryId) return; categoryService.get(categoryId).then((category) => { if (!category) throw new Error('Category not found.'); setName(category.name); setType(category.type); setIcon(isCategoryIcon(category.icon) ? category.icon : fallbackCategoryIcon); }, (cause) => setGeneralError(cause instanceof Error ? cause.message : 'Unable to load category.')).finally(() => setLoading(false)); }, [categoryId]);
  async function save() { setSaving(true); setErrors({}); setGeneralError(undefined); try { const input = { name, type, icon }; if (categoryId) await categoryService.update(categoryId, input); else await categoryService.create(input); router.back(); } catch (cause) { if (cause instanceof CategoryValidationError) setErrors(cause.fields); else setGeneralError(cause instanceof Error ? cause.message : 'Unable to save category.'); } finally { setSaving(false); } }
  if (loading) return <View style={[styles.loading, { backgroundColor: theme.appBackground }]}><ActivityIndicator color={theme.primaryAction} /></View>;
  return <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : 'height'} style={[styles.flex, { backgroundColor: theme.appBackground }]}>
    <View style={[styles.header, { borderBottomColor: theme.border, paddingTop: insets.top + spacing.sm }]}><Pressable accessibilityLabel="Close category form" onPress={() => router.back()} style={styles.headerButton}><SymbolView name={{ ios: 'xmark', android: 'close', web: 'close' }} size={24} tintColor={theme.primaryText} /></Pressable><Text style={[styles.headerTitle, { color: theme.primaryText }]}>{categoryId ? 'Edit Category' : 'New Category'}</Text><View style={styles.headerButton} /></View>
    <ScrollView contentContainerStyle={[styles.content, { paddingBottom: insets.bottom + spacing.xxl }]} keyboardShouldPersistTaps="handled">
      {generalError ? <Text accessibilityLiveRegion="assertive" style={[styles.error, { color: theme.destructive }]}>{generalError}</Text> : null}
      <View style={styles.field}><Text style={[styles.label, { color: theme.primaryText }]}>Category name</Text><TextInput accessibilityLabel="Category name" onChangeText={setName} value={name} style={[styles.input, { backgroundColor: theme.surface, borderColor: errors.name ? theme.destructive : theme.border, color: theme.primaryText }]} />{errors.name ? <Text style={[styles.error, { color: theme.destructive }]}>{errors.name}</Text> : null}</View>
      <View style={styles.field}><Text style={[styles.label, { color: theme.primaryText }]}>Category type</Text><View style={styles.row}>{(['expense', 'income'] as CategoryType[]).map((value) => <Pressable accessibilityRole="radio" accessibilityState={{ selected: type === value }} key={value} onPress={() => setType(value)} style={[styles.choice, { backgroundColor: type === value ? theme.selectedNavigationBackground : theme.surface, borderColor: type === value ? theme.primaryAction : theme.border }]}><Text style={{ color: theme.primaryText }}>{value === 'expense' ? 'Expense' : 'Income'}</Text></Pressable>)}</View>{errors.type ? <Text style={[styles.error, { color: theme.destructive }]}>{errors.type}</Text> : null}</View>
      <View style={styles.field}><Text style={[styles.label, { color: theme.primaryText }]}>Icon</Text><TextInput accessibilityLabel="Search category icons" onChangeText={setIconSearch} placeholder="Search icons" placeholderTextColor={theme.mutedText} value={iconSearch} style={[styles.input, { backgroundColor: theme.surface, borderColor: theme.border, color: theme.primaryText }]} />{categoryIconGroupNames.map((group) => { const values = searchCategoryIcons(iconSearch).filter((value) => categoryIconCatalog[value].group === group); if (!values.length) return null; return <View key={group} style={styles.iconGroup}><Text style={[styles.groupLabel, { color: theme.secondaryText }]}>{group}</Text><View accessibilityRole="radiogroup" style={styles.icons}>{values.map((value) => { const selected = icon === value; const definition = categoryIconCatalog[value]; return <Pressable accessibilityLabel={`${definition.label} icon`} accessibilityHint={`Category icon in ${definition.group}`} accessibilityRole="radio" accessibilityState={{ selected }} key={value} onPress={() => setIcon(value)} style={[styles.icon, { backgroundColor: selected ? theme.selectedNavigationBackground : theme.surface, borderColor: selected ? theme.primaryAction : theme.border, borderWidth: selected ? 3 : borderWidths.thin }]}><SymbolView name={definition.symbol} size={24} tintColor={selected ? theme.primaryAction : theme.primaryText} />{selected ? <View style={[styles.selectedMark, { backgroundColor: theme.primaryAction }]}><SymbolView name={{ ios: 'checkmark', android: 'check', web: 'check' }} size={10} tintColor={theme.onPrimaryAction} /></View> : null}</Pressable>; })}</View></View>; })}{searchCategoryIcons(iconSearch).length === 0 ? <Text style={[styles.error, { color: theme.secondaryText }]}>No matching icons.</Text> : null}{errors.icon ? <Text style={[styles.error, { color: theme.destructive }]}>{errors.icon}</Text> : null}</View>
      <Pressable accessibilityRole="button" disabled={saving} onPress={() => void save()} style={[styles.save, { backgroundColor: saving ? theme.disabledSurface : theme.primaryAction }]}>{saving ? <ActivityIndicator color={theme.disabledText} /> : <Text style={[styles.saveText, { color: theme.onPrimaryAction }]}>Save Category</Text>}</Pressable>
    </ScrollView>
  </KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ flex: { flex: 1 }, loading: { alignItems: 'center', flex: 1, justifyContent: 'center' }, header: { alignItems: 'center', borderBottomWidth: borderWidths.thin, flexDirection: 'row', minHeight: 64, paddingHorizontal: spacing.sm }, headerButton: { alignItems: 'center', height: 48, justifyContent: 'center', width: 48 }, headerTitle: { ...typography.sectionTitle, flex: 1, textAlign: 'center' }, content: { gap: spacing.lg, padding: spacing.md }, field: { gap: spacing.sm }, label: { ...typography.body, fontWeight: '700' }, input: { ...typography.body, borderRadius: borderRadii.md, borderWidth: borderWidths.thin, minHeight: 52, paddingHorizontal: spacing.md }, row: { flexDirection: 'row', gap: spacing.sm }, choice: { alignItems: 'center', borderRadius: borderRadii.md, borderWidth: borderWidths.thin, flex: 1, justifyContent: 'center', minHeight: 48 }, iconGroup: { gap: spacing.sm }, groupLabel: { ...typography.label, textTransform: 'uppercase' }, icons: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, icon: { alignItems: 'center', borderRadius: borderRadii.md, height: 56, justifyContent: 'center', position: 'relative', width: 56 }, selectedMark: { alignItems: 'center', borderRadius: borderRadii.full, height: 18, justifyContent: 'center', position: 'absolute', right: 2, top: 2, width: 18 }, error: { ...typography.caption }, save: { alignItems: 'center', borderRadius: borderRadii.md, justifyContent: 'center', minHeight: 52 }, saveText: { ...typography.body, fontWeight: '700' } });
