import { SymbolView } from 'expo-symbols';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View, type AlertButton } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { borderRadii, borderWidths, spacing, typography } from '@/constants/theme';
import { useAppTheme } from '@/hooks/use-app-theme';
import { getCategoryIcon } from '../category-icons';
import { CategoryActionError } from '../category.service';
import { categoryService } from '../categories';
import type { Category, CategoryType } from '../category.types';
import { useCategories } from '../use-categories';

export function CategoriesScreen({ initialType = 'expense' }: { initialType?: CategoryType }) {
  const router = useRouter(); const insets = useSafeAreaInsets(); const theme = useAppTheme(); const [type, setType] = useState<CategoryType>(initialType); const [showArchived, setShowArchived] = useState(false); const [actionError, setActionError] = useState<string>();
  const { categories, loading, error, reload } = useCategories(type, true); const active = categories.filter((item) => !item.isArchived); const archived = categories.filter((item) => item.isArchived);
  async function actions(category: Category) { setActionError(undefined); try { const canDelete = await categoryService.canPermanentlyDelete(category.id); const options: AlertButton[] = [{ text: 'Cancel', style: 'cancel' }, { text: 'Edit', onPress: () => router.push({ pathname: '/category-form', params: { id: category.id } }) }]; if (category.isArchived) options.push({ text: 'Restore category', onPress: () => void run(() => categoryService.restore(category.id), 'restore') }); else options.push({ text: 'Archive', onPress: () => void run(() => categoryService.archive(category.id), 'archive') }); if (canDelete) options.push({ text: 'Delete permanently', style: 'destructive', onPress: () => confirmDelete(category) }); Alert.alert(category.name, 'Choose a category action.', options); } catch (cause) { setActionError(cause instanceof Error ? cause.message : 'Unable to load category actions.'); } }
  async function run(operation: () => Promise<void>, label: string) { try { await operation(); await reload(); } catch (cause) { if (cause instanceof CategoryActionError) Alert.alert(`Unable to ${label} category`, cause.message); else setActionError(cause instanceof Error ? cause.message : `Unable to ${label} category.`); } }
  function confirmDelete(category: Category) { Alert.alert('Delete category permanently?', `${category.name} will be permanently deleted. This cannot be undone.`, [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete permanently', style: 'destructive', onPress: () => void run(() => categoryService.permanentlyDelete(category.id), 'delete') }]); }
  const render = (items: Category[]) => items.map((category) => { const icon = getCategoryIcon(category.icon); return <Pressable accessibilityLabel={`${category.name}, ${category.isArchived ? 'archived' : 'active'}`} key={category.id} onPress={() => void actions(category)} style={[styles.card, { backgroundColor: category.isArchived ? theme.disabledSurface : theme.surface, borderColor: theme.border }]}><SymbolView name={icon} size={26} tintColor={type === 'income' ? theme.income : theme.expense} /><View style={styles.identity}><Text style={[styles.name, { color: theme.primaryText }]}>{category.name}</Text><Text style={[styles.status, { color: theme.secondaryText }]}>{category.isArchived ? 'Archived' : type === 'income' ? 'Income' : 'Expense'}</Text></View><SymbolView name={{ ios: 'ellipsis', android: 'more_vert', web: 'more_vert' }} size={22} tintColor={theme.secondaryText} /></Pressable>; });
  return <View style={[styles.screen, { backgroundColor: theme.appBackground, paddingTop: insets.top }]}><View style={styles.header}><Pressable accessibilityLabel="Close categories" onPress={() => router.back()} style={styles.headerButton}><SymbolView name={{ ios: 'xmark', android: 'close', web: 'close' }} size={24} tintColor={theme.primaryText} /></Pressable><Text style={[styles.title, { color: theme.primaryText }]}>Categories</Text><Pressable accessibilityLabel="Add category" onPress={() => router.push({ pathname: '/category-form', params: { type } })} style={styles.headerButton}><SymbolView name={{ ios: 'plus', android: 'add', web: 'add' }} size={26} tintColor={theme.primaryAction} /></Pressable></View><ScrollView contentContainerStyle={[styles.content, { paddingBottom: insets.bottom + spacing.xl }]}><View style={[styles.selector, { backgroundColor: theme.elevatedSurface }]}>{(['expense', 'income'] as CategoryType[]).map((value) => <Pressable key={value} onPress={() => setType(value)} style={[styles.selectorButton, type === value && { backgroundColor: value === 'income' ? theme.income : theme.expense }]}><Text style={{ color: type === value ? theme.onPrimaryAction : theme.secondaryText, fontWeight: '700' }}>{value === 'expense' ? 'Expense' : 'Income'}</Text></Pressable>)}</View>{actionError ? <Text style={[styles.error, { color: theme.destructive }]}>{actionError}</Text> : null}{loading ? <ActivityIndicator color={theme.primaryAction} /> : null}{error ? <Text style={[styles.error, { color: theme.destructive }]}>{error}</Text> : null}{!loading && !error && active.length === 0 ? <Text style={[styles.empty, { color: theme.secondaryText }]}>No active {type} categories.</Text> : render(active)}{archived.length ? <><Pressable onPress={() => setShowArchived((value) => !value)} style={styles.archivedToggle}><Text style={[styles.sectionTitle, { color: theme.primaryText }]}>Archived ({archived.length})</Text><Text style={{ color: theme.primaryAction }}>{showArchived ? 'Hide' : 'Show'}</Text></Pressable>{showArchived ? render(archived) : null}</> : null}</ScrollView></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1 }, header: { alignItems: 'center', flexDirection: 'row', minHeight: 64, paddingHorizontal: spacing.sm }, headerButton: { alignItems: 'center', height: 48, justifyContent: 'center', width: 48 }, title: { ...typography.title, flex: 1, fontSize: 26, textAlign: 'center' }, content: { gap: spacing.md, padding: spacing.md }, selector: { borderRadius: borderRadii.md, flexDirection: 'row', padding: spacing.xs }, selectorButton: { alignItems: 'center', borderRadius: borderRadii.sm, flex: 1, justifyContent: 'center', minHeight: 48 }, card: { alignItems: 'center', borderRadius: borderRadii.md, borderWidth: borderWidths.thin, flexDirection: 'row', gap: spacing.md, minHeight: 72, padding: spacing.md }, identity: { flex: 1 }, name: { ...typography.body, fontWeight: '700' }, status: { ...typography.caption }, archivedToggle: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', minHeight: 48 }, sectionTitle: { ...typography.sectionTitle }, error: { ...typography.caption }, empty: { ...typography.body, paddingVertical: spacing.xl, textAlign: 'center' } });
