import { SymbolView } from 'expo-symbols';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View, type AlertButton } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { IconChip } from '@/components/icon-chip';
import { borderRadii, spacing, typography } from '@/constants/theme';
import { toUserMessage } from '@/errors/user-error';
import { useAppTheme } from '@/hooks/use-app-theme';
import { getCategoryIcon } from '../category-icons';
import { CategoryActionError } from '../category.service';
import { categoryService } from '../categories';
import type { Category, CategoryType } from '../category.types';
import { useCategories } from '../use-categories';

export function CategoriesScreen({ initialType = 'expense' }: { initialType?: CategoryType }) {
  const router = useRouter(); const insets = useSafeAreaInsets(); const theme = useAppTheme(); const [type, setType] = useState<CategoryType>(initialType); const [showArchived, setShowArchived] = useState(false); const [actionError, setActionError] = useState<string>(); const [busyId, setBusyId] = useState<string | null>(null); const busy = busyId !== null;
  const { categories, loading, error, reload } = useCategories(type, true); const active = categories.filter((item) => !item.isArchived); const archived = categories.filter((item) => item.isArchived);
  async function actions(category: Category) { if (busy) return; setActionError(undefined); try { const canDelete = await categoryService.canPermanentlyDelete(category.id); const options: AlertButton[] = [{ text: 'Cancel', style: 'cancel' }, { text: 'Edit', onPress: () => router.push({ pathname: '/category-form', params: { id: category.id } }) }]; if (category.isArchived) options.push({ text: 'Restore category', onPress: () => void run(() => categoryService.restore(category.id), 'restore', category.id) }); else options.push({ text: 'Archive', onPress: () => void run(() => categoryService.archive(category.id), 'archive', category.id) }); if (canDelete) options.push({ text: 'Delete permanently', style: 'destructive', onPress: () => confirmDelete(category) }); Alert.alert(category.name, 'Choose a category action.', options); } catch (cause) { setActionError(toUserMessage(cause, 'Unable to load category actions.')); } }
  async function run(operation: () => Promise<void>, label: string, id: string) { if (busy) return; setBusyId(id); try { await operation(); await reload(); } catch (cause) { if (cause instanceof CategoryActionError) Alert.alert(`Unable to ${label} category`, cause.message); else setActionError(toUserMessage(cause, `Unable to ${label} category.`)); } finally { setBusyId(null); } }
  function confirmDelete(category: Category) { if (busy) return; Alert.alert('Delete category permanently?', `${category.name} will be permanently deleted. This cannot be undone.`, [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete permanently', style: 'destructive', onPress: () => void run(() => categoryService.permanentlyDelete(category.id), 'delete', category.id) }]); }
  const render = (items: Category[]) => <View style={styles.grid}>{items.map((category) => { const icon = getCategoryIcon(category.icon); return <Pressable accessibilityLabel={`${category.name}, ${category.isArchived ? 'archived' : 'active'}`} accessibilityRole="button" accessibilityState={{ disabled: busy, busy: busyId === category.id }} disabled={busy} key={category.id} onPress={() => void actions(category)} style={[styles.card, { backgroundColor: category.isArchived ? theme.disabledSurface : theme.surface, opacity: busy && busyId !== category.id ? 0.5 : 1 }]}><View style={styles.cardTop}><IconChip icon={icon} color={type === 'income' ? theme.income : theme.expense} background={type === 'income' ? theme.tintIncome : theme.tintExpense} size={44} iconSize={24} /><SymbolView name={{ ios: 'ellipsis', android: 'more_vert', web: 'more_vert' }} size={22} tintColor={theme.secondaryText} /></View><View style={styles.identity}><Text numberOfLines={1} style={[styles.name, { color: theme.primaryText }]}>{category.name}</Text><Text style={[styles.status, { color: theme.secondaryText }]}>{category.isArchived ? 'Archived' : type === 'income' ? 'Income' : 'Expense'}</Text></View></Pressable>; })}</View>;
  return <View style={[styles.screen, { backgroundColor: theme.appBackground, paddingTop: insets.top }]}><View style={styles.header}><Pressable accessibilityLabel="Close categories" onPress={() => router.back()} style={styles.headerButton}><SymbolView name={{ ios: 'xmark', android: 'close', web: 'close' }} size={24} tintColor={theme.primaryText} /></Pressable><Text style={[styles.title, { color: theme.primaryText }]}>Categories</Text><Pressable accessibilityLabel="Add category" onPress={() => router.push({ pathname: '/category-form', params: { type } })} style={styles.headerButton}><SymbolView name={{ ios: 'plus', android: 'add', web: 'add' }} size={26} tintColor={theme.primaryAction} /></Pressable></View><ScrollView contentContainerStyle={[styles.content, { paddingBottom: insets.bottom + spacing.xl }]}><View style={[styles.selector, { backgroundColor: theme.elevatedSurface }]}>{(['expense', 'income'] as CategoryType[]).map((value) => <Pressable key={value} onPress={() => setType(value)} style={[styles.selectorButton, type === value && { backgroundColor: value === 'income' ? theme.income : theme.expense }]}><Text style={{ color: type === value ? theme.onPrimaryAction : theme.secondaryText, fontWeight: '700' }}>{value === 'expense' ? 'Expense' : 'Income'}</Text></Pressable>)}</View>{actionError ? <Text style={[styles.error, { color: theme.destructive }]}>{actionError}</Text> : null}{loading ? <ActivityIndicator color={theme.primaryAction} /> : null}{error ? <Text style={[styles.error, { color: theme.destructive }]}>{error}</Text> : null}{!loading && !error && active.length === 0 ? <Text style={[styles.empty, { color: theme.secondaryText }]}>No active {type} categories.</Text> : render(active)}{archived.length ? <><Pressable onPress={() => setShowArchived((value) => !value)} style={styles.archivedToggle}><Text style={[styles.sectionTitle, { color: theme.primaryText }]}>Archived ({archived.length})</Text><Text style={{ color: theme.primaryAction }}>{showArchived ? 'Hide' : 'Show'}</Text></Pressable>{showArchived ? render(archived) : null}</> : null}</ScrollView></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1 }, header: { alignItems: 'center', flexDirection: 'row', minHeight: 64, paddingHorizontal: spacing.sm }, headerButton: { alignItems: 'center', height: 48, justifyContent: 'center', width: 48 }, title: { ...typography.title, flex: 1, fontSize: 26, textAlign: 'center' }, content: { gap: spacing.md, padding: spacing.md }, selector: { borderRadius: borderRadii.md, flexDirection: 'row', padding: spacing.xs }, selectorButton: { alignItems: 'center', borderRadius: borderRadii.sm, flex: 1, justifyContent: 'center', minHeight: 48 }, grid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', rowGap: spacing.md }, card: { borderRadius: borderRadii.card, gap: spacing.md, justifyContent: 'space-between', minHeight: 120, padding: spacing.md, width: '48.5%' }, cardTop: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, identity: {}, name: { ...typography.body, fontWeight: '700' }, status: { ...typography.caption }, archivedToggle: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', minHeight: 48 }, sectionTitle: { ...typography.sectionTitle }, error: { ...typography.caption }, empty: { ...typography.body, paddingVertical: spacing.xl, textAlign: 'center' } });
