import assert from 'node:assert/strict'; import test from 'node:test';
import { groupTransactions } from '../src/features/transactions/transaction-presentation.ts'; import { bogotaToday, isValidCalendarDate } from '../src/features/transactions/transaction-date.ts'; import { TransactionService, TransactionValidationError } from '../src/features/transactions/transaction.service.ts';
import { subscribeToFinancialDataChanges } from '../src/features/transactions/financial-data-events.ts';
const NOW = '2026-07-12T15:30:00.000Z';
class Repo { records=[]; async create(value){this.records.push({...value});} async list(){return this.records;} async recent(limit){return this.records.slice(0,limit);} async summarizeMonth(){return {income:0,expenses:0,net:0};} }
class Accounts { values=new Map([['active',{id:'active',isArchived:false}],['archived',{id:'archived',isArchived:true}],['card',{id:'card',isArchived:false,type:'credit_card'}]]); async findById(id){return this.values.get(id)??null;} }
class Categories { values=new Map([['expense',{id:'expense',type:'expense',isArchived:false}],['income',{id:'income',type:'income',isArchived:false}],['archived',{id:'archived',type:'expense',isArchived:true}]]); async findById(id){return this.values.get(id)??null;} }
function setup(){const repository=new Repo();return {repository,service:new TransactionService(repository,new Accounts(),new Categories(),()=> 'tx-1',()=>NOW)};}
const valid={type:'expense',amount:50000,accountId:'active',categoryId:'expense',transactionDate:'2026-07-12',note:' lunch '};
async function fields(action){try{await action();}catch(error){assert.ok(error instanceof TransactionValidationError);return error.fields;}throw new Error('Expected validation error');}
test('creates a posted expense with positive magnitude and trimmed note',async()=>{const {service}=setup();const value=await service.create(valid);assert.equal(value.type,'expense');assert.equal(value.amount,50000);assert.equal(value.note,'lunch');assert.equal(value.status,'posted');assert.equal(value.destinationAccountId,null);assert.equal(value.createdAt,NOW);assert.equal(value.updatedAt,NOW);});
test('creates a valid income',async()=>{const {service}=setup();assert.equal((await service.create({...valid,type:'income',categoryId:'income'})).type,'income');});
test('rejects unsupported transaction types',async()=>{assert.ok((await fields(()=>setup().service.create({...valid,type:'transfer'}))).type);});
for(const amount of [0,-1,1.5,Number.MAX_SAFE_INTEGER+1])test(`rejects invalid amount ${amount}`,async()=>{assert.ok((await fields(()=>setup().service.create({...valid,amount}))).amount);});
test('rejects missing and archived accounts',async()=>{assert.ok((await fields(()=>setup().service.create({...valid,accountId:''}))).accountId);assert.ok((await fields(()=>setup().service.create({...valid,accountId:'archived'}))).accountId);});
test('rejects missing and archived categories',async()=>{assert.ok((await fields(()=>setup().service.create({...valid,categoryId:''}))).categoryId);assert.ok((await fields(()=>setup().service.create({...valid,categoryId:'archived'}))).categoryId);});
test('rejects category type mismatches',async()=>{assert.ok((await fields(()=>setup().service.create({...valid,categoryId:'income'}))).categoryId);assert.ok((await fields(()=>setup().service.create({...valid,type:'income',categoryId:'expense'}))).categoryId);});
test('validates and preserves Bogotá-local calendar dates',async()=>{const {service}=setup();assert.equal((await service.create(valid)).transactionDate,'2026-07-12');assert.equal(isValidCalendarDate('2026-02-30'),false);assert.equal(bogotaToday(new Date('2026-07-13T02:00:00Z')),'2026-07-12');});
test('normalizes blank notes to null and enforces length',async()=>{const {service}=setup();assert.equal((await service.create({...valid,note:'   '})).note,null);assert.ok((await fields(()=>service.create({...valid,note:'x'.repeat(201)}))).note);});
test('groups already-sorted transactions by financial date',()=>{const items=[{id:'new',transactionDate:'2026-07-12'},{id:'older',transactionDate:'2026-07-11'}];const groups=groupTransactions(items);assert.deepEqual(groups.map(g=>g.id),['2026-07-12','2026-07-11']);});
test('notifies financial views only after transaction creation succeeds',async()=>{const {service}=setup();let refreshes=0;const unsubscribe=subscribeToFinancialDataChanges(()=>{refreshes+=1;});await service.create(valid);unsubscribe();assert.equal(refreshes,1);});
