import { SymbolView } from 'expo-symbols';
import { useRouter, type Href } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { borderRadii, borderWidths, spacing, typography } from '@/constants/theme';
import { useAppTheme } from '@/hooks/use-app-theme';

export function MoreScreen() {
  const router = useRouter(); const insets = useSafeAreaInsets(); const theme = useAppTheme();
  return <View style={[styles.screen, { backgroundColor: theme.appBackground, paddingTop: insets.top }]}>
    <View style={styles.header}><Pressable accessibilityLabel="Close More" accessibilityRole="button" onPress={() => router.back()} style={styles.headerButton}><SymbolView name={{ ios: 'xmark', android: 'close', web: 'close' }} size={24} tintColor={theme.primaryText} /></Pressable><Text accessibilityRole="header" style={[styles.title, { color: theme.primaryText }]}>More</Text><View style={styles.headerButton} /></View>
    <ScrollView contentContainerStyle={[styles.content, { paddingBottom: insets.bottom + spacing.lg }]}>
      <Pressable accessibilityLabel="Open security settings" accessibilityHint="Configure PIN, device biometrics, and automatic App Lock" accessibilityRole="button" onPress={() => router.push('/security' as Href)} style={[styles.row, { backgroundColor: theme.surface, borderColor: theme.border }]}><View style={[styles.icon, { backgroundColor: theme.elevatedSurface }]}><SymbolView name={{ ios: 'lock.shield.fill', android: 'shield_lock', web: 'lock' }} size={24} tintColor={theme.primaryAction} /></View><View style={styles.text}><Text style={[styles.label, { color: theme.primaryText }]}>Security</Text><Text style={[styles.description, { color: theme.secondaryText }]}>PIN, biometrics, and automatic locking</Text></View><SymbolView name={{ ios: 'chevron.right', android: 'chevron_right', web: 'chevron_right' }} size={22} tintColor={theme.mutedText} /></Pressable>
      <Pressable accessibilityLabel="Open notification settings" accessibilityHint="Configure local recurring, budget, and daily reminders" accessibilityRole="button" onPress={() => router.push('/notifications-settings' as Href)} style={[styles.row, { backgroundColor: theme.surface, borderColor: theme.border }]}><View style={[styles.icon, { backgroundColor: theme.elevatedSurface }]}><SymbolView name={{ ios: 'bell.badge.fill', android: 'notifications', web: 'notifications' }} size={24} tintColor={theme.primaryAction} /></View><View style={styles.text}><Text style={[styles.label, { color: theme.primaryText }]}>Notifications</Text><Text style={[styles.description, { color: theme.secondaryText }]}>Local reminders and notification privacy</Text></View><SymbolView name={{ ios: 'chevron.right', android: 'chevron_right', web: 'chevron_right' }} size={22} tintColor={theme.mutedText} /></Pressable>
      <Pressable accessibilityLabel="Open backup and restore" accessibilityHint="Create a local backup or replace local data from a backup file" accessibilityRole="button" onPress={() => router.push('/backup' as Href)} style={[styles.row, { backgroundColor: theme.surface, borderColor: theme.border }]}><View style={[styles.icon, { backgroundColor: theme.elevatedSurface }]}><SymbolView name={{ ios: 'externaldrive.fill', android: 'backup', web: 'backup' }} size={24} tintColor={theme.primaryAction} /></View><View style={styles.text}><Text style={[styles.label, { color: theme.primaryText }]}>Backup & Restore</Text><Text style={[styles.description, { color: theme.secondaryText }]}>Save or restore a complete local copy</Text></View><SymbolView name={{ ios: 'chevron.right', android: 'chevron_right', web: 'chevron_right' }} size={22} tintColor={theme.mutedText} /></Pressable>
      <Pressable accessibilityLabel="Open reports" accessibilityHint="Review income, expenses, categories, net worth, and period comparisons" accessibilityRole="button" onPress={() => router.push('/reports' as Href)} style={[styles.row, { backgroundColor: theme.surface, borderColor: theme.border }]}><View style={[styles.icon, { backgroundColor: theme.elevatedSurface }]}><SymbolView name={{ ios: 'chart.xyaxis.line', android: 'query_stats', web: 'query_stats' }} size={24} tintColor={theme.primaryAction} /></View><View style={styles.text}><Text style={[styles.label, { color: theme.primaryText }]}>Reports</Text><Text style={[styles.description, { color: theme.secondaryText }]}>Explore cash flow, categories, and net worth</Text></View><SymbolView name={{ ios: 'chevron.right', android: 'chevron_right', web: 'chevron_right' }} size={22} tintColor={theme.mutedText} /></Pressable>
      <Pressable accessibilityLabel="Manage categories" accessibilityHint="Create, edit, archive, and restore categories" accessibilityRole="button" onPress={() => router.push('/categories')} style={[styles.row, { backgroundColor: theme.surface, borderColor: theme.border }]}><View style={[styles.icon, { backgroundColor: theme.elevatedSurface }]}><SymbolView name={{ ios: 'square.grid.2x2.fill', android: 'category', web: 'category' }} size={24} tintColor={theme.primaryAction} /></View><View style={styles.text}><Text style={[styles.label, { color: theme.primaryText }]}>Categories</Text><Text style={[styles.description, { color: theme.secondaryText }]}>Manage expense and income categories</Text></View><SymbolView name={{ ios: 'chevron.right', android: 'chevron_right', web: 'chevron_right' }} size={22} tintColor={theme.mutedText} /></Pressable>
      <Pressable accessibilityLabel="Manage recurring transactions" accessibilityHint="Review due occurrences and manage recurring rules" accessibilityRole="button" onPress={() => router.push('/recurring')} style={[styles.row, { backgroundColor: theme.surface, borderColor: theme.border }]}><View style={[styles.icon, { backgroundColor: theme.elevatedSurface }]}><SymbolView name={{ ios: 'repeat', android: 'repeat', web: 'repeat' }} size={24} tintColor={theme.primaryAction} /></View><View style={styles.text}><Text style={[styles.label, { color: theme.primaryText }]}>Recurring Transactions</Text><Text style={[styles.description, { color: theme.secondaryText }]}>Review, confirm, pause, and schedule recurring items</Text></View><SymbolView name={{ ios: 'chevron.right', android: 'chevron_right', web: 'chevron_right' }} size={22} tintColor={theme.mutedText} /></Pressable>
    </ScrollView>
  </View>;
}
const styles = StyleSheet.create({ screen: { flex: 1 }, header: { alignItems: 'center', flexDirection: 'row', minHeight: 64, paddingHorizontal: spacing.sm }, headerButton: { alignItems: 'center', height: 48, justifyContent: 'center', width: 48 }, title: { ...typography.title, flex: 1, fontSize: 26, textAlign: 'center' }, content: { gap: spacing.md, padding: spacing.md }, row: { alignItems: 'center', borderRadius: borderRadii.md, borderWidth: borderWidths.thin, flexDirection: 'row', gap: spacing.md, minHeight: 76, padding: spacing.md }, icon: { alignItems: 'center', borderRadius: borderRadii.md, height: 44, justifyContent: 'center', width: 44 }, text: { flex: 1 }, label: { ...typography.body, fontWeight: '700' }, description: { ...typography.caption } });
