import type { SymbolViewProps } from 'expo-symbols';

export const categoryIconGroupNames = ['Food', 'Home & utilities', 'Transportation', 'Shopping', 'Health', 'Personal care', 'Education', 'Entertainment', 'Travel', 'Finance', 'Work & income', 'Family & pets', 'Other'] as const;
export type CategoryIconGroup = (typeof categoryIconGroupNames)[number];

type CategoryIconDefinition = { label: string; group: CategoryIconGroup; keywords: string; symbol: SymbolViewProps['name'] };

/**
 * Curated icon catalog. Keys are persisted on `categories.icon`, so an existing
 * key is never renamed or removed — only new ones are appended. Each symbol
 * pairs an SF Symbol (iOS) with a Material Symbol (Android/web); both names must
 * exist or the icon renders blank on that platform.
 */
export const categoryIconCatalog = {
  food: { label: 'Food', group: 'Food', keywords: 'meal dining', symbol: { ios: 'fork.knife', android: 'restaurant', web: 'restaurant' } },
  groceries: { label: 'Groceries', group: 'Food', keywords: 'market food basket supermarket', symbol: { ios: 'basket.fill', android: 'grocery', web: 'grocery' } },
  restaurant: { label: 'Restaurant', group: 'Food', keywords: 'dinner lunch takeout', symbol: { ios: 'takeoutbag.and.cup.and.straw.fill', android: 'local_dining', web: 'local_dining' } },
  coffee: { label: 'Coffee', group: 'Food', keywords: 'cafe drink tea', symbol: { ios: 'cup.and.saucer.fill', android: 'local_cafe', web: 'local_cafe' } },
  bar: { label: 'Bar & drinks', group: 'Food', keywords: 'alcohol wine beer', symbol: { ios: 'wineglass.fill', android: 'local_bar', web: 'local_bar' } },
  dessert: { label: 'Dessert', group: 'Food', keywords: 'sweets cake bakery ice cream', symbol: { ios: 'birthday.cake.fill', android: 'icecream', web: 'icecream' } },
  'food-delivery': { label: 'Food delivery', group: 'Food', keywords: 'takeaway courier domicilio', symbol: { ios: 'moped.fill', android: 'delivery_dining', web: 'delivery_dining' } },
  bills: { label: 'Bills', group: 'Home & utilities', keywords: 'receipt utilities invoice', symbol: { ios: 'doc.text.fill', android: 'receipt_long', web: 'receipt_long' } },
  home: { label: 'Home', group: 'Home & utilities', keywords: 'house household', symbol: { ios: 'house.fill', android: 'home', web: 'home' } },
  rent: { label: 'Rent', group: 'Home & utilities', keywords: 'lease apartment arriendo', symbol: { ios: 'building.2.fill', android: 'apartment', web: 'apartment' } },
  mortgage: { label: 'Mortgage', group: 'Home & utilities', keywords: 'housing loan property hipoteca', symbol: { ios: 'house.and.flag.fill', android: 'real_estate_agent', web: 'real_estate_agent' } },
  electricity: { label: 'Electricity', group: 'Home & utilities', keywords: 'power energy light', symbol: { ios: 'bolt.fill', android: 'bolt', web: 'bolt' } },
  water: { label: 'Water', group: 'Home & utilities', keywords: 'utility drop', symbol: { ios: 'drop.fill', android: 'water_drop', web: 'water_drop' } },
  gas: { label: 'Gas', group: 'Home & utilities', keywords: 'heating utility flame', symbol: { ios: 'flame.fill', android: 'local_fire_department', web: 'local_fire_department' } },
  internet: { label: 'Internet', group: 'Home & utilities', keywords: 'wifi broadband router', symbol: { ios: 'wifi', android: 'wifi', web: 'wifi' } },
  phone: { label: 'Phone', group: 'Home & utilities', keywords: 'mobile cellular', symbol: { ios: 'iphone', android: 'smartphone', web: 'smartphone' } },
  furniture: { label: 'Furniture', group: 'Home & utilities', keywords: 'sofa chair decor', symbol: { ios: 'sofa.fill', android: 'chair', web: 'chair' } },
  appliances: { label: 'Appliances', group: 'Home & utilities', keywords: 'kitchen fridge white goods', symbol: { ios: 'refrigerator.fill', android: 'kitchen', web: 'kitchen' } },
  maintenance: { label: 'Repairs', group: 'Home & utilities', keywords: 'handyman tools fix plumbing', symbol: { ios: 'wrench.and.screwdriver.fill', android: 'handyman', web: 'handyman' } },
  cleaning: { label: 'Cleaning', group: 'Home & utilities', keywords: 'housekeeping chores aseo', symbol: { ios: 'sparkles', android: 'cleaning_services', web: 'cleaning_services' } },
  garden: { label: 'Garden', group: 'Home & utilities', keywords: 'yard plants outdoor', symbol: { ios: 'leaf.fill', android: 'yard', web: 'yard' } },
  waste: { label: 'Waste', group: 'Home & utilities', keywords: 'garbage trash recycling basura', symbol: { ios: 'trash.fill', android: 'delete', web: 'delete' } },
  'home-security': { label: 'Home security', group: 'Home & utilities', keywords: 'alarm monitoring lock', symbol: { ios: 'lock.shield.fill', android: 'security', web: 'security' } },
  transport: { label: 'Car', group: 'Transportation', keywords: 'transport vehicle drive', symbol: { ios: 'car.fill', android: 'directions_car', web: 'directions_car' } },
  bus: { label: 'Public transit', group: 'Transportation', keywords: 'bus metro transmilenio', symbol: { ios: 'bus.fill', android: 'directions_bus', web: 'directions_bus' } },
  train: { label: 'Train', group: 'Transportation', keywords: 'rail tram subway', symbol: { ios: 'tram.fill', android: 'train', web: 'train' } },
  taxi: { label: 'Taxi & rideshare', group: 'Transportation', keywords: 'uber cab didi', symbol: { ios: 'car.2.fill', android: 'local_taxi', web: 'local_taxi' } },
  bike: { label: 'Bike', group: 'Transportation', keywords: 'bicycle cycling scooter', symbol: { ios: 'bicycle', android: 'pedal_bike', web: 'pedal_bike' } },
  ferry: { label: 'Ferry', group: 'Transportation', keywords: 'boat ship water', symbol: { ios: 'ferry.fill', android: 'directions_boat', web: 'directions_boat' } },
  fuel: { label: 'Fuel', group: 'Transportation', keywords: 'gas petrol gasolina', symbol: { ios: 'fuelpump.fill', android: 'local_gas_station', web: 'local_gas_station' } },
  'ev-charging': { label: 'EV charging', group: 'Transportation', keywords: 'electric car battery', symbol: { ios: 'bolt.car.fill', android: 'electric_car', web: 'electric_car' } },
  parking: { label: 'Parking', group: 'Transportation', keywords: 'car garage', symbol: { ios: 'parkingsign.circle.fill', android: 'local_parking', web: 'local_parking' } },
  toll: { label: 'Tolls', group: 'Transportation', keywords: 'peaje highway road', symbol: { ios: 'road.lanes', android: 'toll', web: 'toll' } },
  'car-service': { label: 'Car service', group: 'Transportation', keywords: 'mechanic repair taller', symbol: { ios: 'wrench.adjustable.fill', android: 'car_repair', web: 'car_repair' } },
  shopping: { label: 'Shopping', group: 'Shopping', keywords: 'bag purchases', symbol: { ios: 'bag.fill', android: 'shopping_bag', web: 'shopping_bag' } },
  cart: { label: 'Shopping cart', group: 'Shopping', keywords: 'store buy', symbol: { ios: 'cart.fill', android: 'shopping_cart', web: 'shopping_cart' } },
  clothing: { label: 'Clothing', group: 'Shopping', keywords: 'fashion apparel ropa', symbol: { ios: 'tshirt.fill', android: 'checkroom', web: 'checkroom' } },
  electronics: { label: 'Electronics', group: 'Shopping', keywords: 'computer tech gadgets', symbol: { ios: 'desktopcomputer', android: 'computer', web: 'computer' } },
  'online-shopping': { label: 'Online shopping', group: 'Shopping', keywords: 'delivery parcel package envio', symbol: { ios: 'shippingbox.fill', android: 'inventory_2', web: 'inventory_2' } },
  mall: { label: 'Mall', group: 'Shopping', keywords: 'centro comercial retail store', symbol: { ios: 'bag.circle.fill', android: 'local_mall', web: 'local_mall' } },
  jewelry: { label: 'Jewelry', group: 'Shopping', keywords: 'watch accessories luxury', symbol: { ios: 'diamond.fill', android: 'diamond', web: 'diamond' } },
  health: { label: 'Health', group: 'Health', keywords: 'medical care salud', symbol: { ios: 'cross.case.fill', android: 'medical_services', web: 'medical_services' } },
  doctor: { label: 'Doctor', group: 'Health', keywords: 'clinic hospital consultation', symbol: { ios: 'stethoscope', android: 'local_hospital', web: 'local_hospital' } },
  pharmacy: { label: 'Pharmacy', group: 'Health', keywords: 'medicine prescription drugs', symbol: { ios: 'pills.fill', android: 'medication', web: 'medication' } },
  lab: { label: 'Lab tests', group: 'Health', keywords: 'exams bloodwork analysis', symbol: { ios: 'cross.vial.fill', android: 'science', web: 'science' } },
  dental: { label: 'Dental', group: 'Health', keywords: 'dentist teeth', symbol: { ios: 'mouth.fill', android: 'dentistry', web: 'dentistry' } },
  vision: { label: 'Vision', group: 'Health', keywords: 'glasses optical eyes', symbol: { ios: 'eyeglasses', android: 'visibility', web: 'visibility' } },
  therapy: { label: 'Therapy', group: 'Health', keywords: 'mental health psychology counseling', symbol: { ios: 'brain.head.profile', android: 'psychology', web: 'psychology' } },
  fitness: { label: 'Fitness', group: 'Health', keywords: 'gym exercise weights', symbol: { ios: 'dumbbell.fill', android: 'fitness_center', web: 'fitness_center' } },
  haircut: { label: 'Haircut', group: 'Personal care', keywords: 'barber salon hair peluqueria', symbol: { ios: 'scissors', android: 'content_cut', web: 'content_cut' } },
  beauty: { label: 'Beauty', group: 'Personal care', keywords: 'cosmetics makeup skincare', symbol: { ios: 'comb.fill', android: 'face', web: 'face' } },
  spa: { label: 'Spa & wellness', group: 'Personal care', keywords: 'massage relax yoga', symbol: { ios: 'figure.mind.and.body', android: 'spa', web: 'spa' } },
  laundry: { label: 'Laundry', group: 'Personal care', keywords: 'dry cleaning washing lavanderia', symbol: { ios: 'washer.fill', android: 'local_laundry_service', web: 'local_laundry_service' } },
  education: { label: 'Education', group: 'Education', keywords: 'school study', symbol: { ios: 'graduationcap.fill', android: 'school', web: 'school' } },
  tuition: { label: 'Tuition', group: 'Education', keywords: 'university fees semester matricula', symbol: { ios: 'graduationcap.circle.fill', android: 'cast_for_education', web: 'cast_for_education' } },
  books: { label: 'Books', group: 'Education', keywords: 'reading library', symbol: { ios: 'books.vertical.fill', android: 'menu_book', web: 'menu_book' } },
  courses: { label: 'Courses', group: 'Education', keywords: 'online training workshop', symbol: { ios: 'laptopcomputer', android: 'co_present', web: 'co_present' } },
  'school-supplies': { label: 'School supplies', group: 'Education', keywords: 'stationery backpack materials utiles', symbol: { ios: 'backpack.fill', android: 'backpack', web: 'backpack' } },
  entertainment: { label: 'Games', group: 'Entertainment', keywords: 'gaming fun console', symbol: { ios: 'gamecontroller.fill', android: 'sports_esports', web: 'sports_esports' } },
  movies: { label: 'Movies', group: 'Entertainment', keywords: 'cinema film', symbol: { ios: 'film.fill', android: 'movie', web: 'movie' } },
  streaming: { label: 'Streaming', group: 'Entertainment', keywords: 'netflix spotify video', symbol: { ios: 'play.rectangle.fill', android: 'subscriptions', web: 'subscriptions' } },
  subscriptions: { label: 'Subscriptions', group: 'Entertainment', keywords: 'recurring membership renewal', symbol: { ios: 'arrow.triangle.2.circlepath', android: 'autorenew', web: 'autorenew' } },
  tv: { label: 'TV', group: 'Entertainment', keywords: 'television cable', symbol: { ios: 'tv.fill', android: 'tv', web: 'tv' } },
  music: { label: 'Music', group: 'Entertainment', keywords: 'audio songs', symbol: { ios: 'music.note', android: 'music_note', web: 'music_note' } },
  concerts: { label: 'Concerts', group: 'Entertainment', keywords: 'tickets events live boletas', symbol: { ios: 'ticket.fill', android: 'local_activity', web: 'local_activity' } },
  theater: { label: 'Theater', group: 'Entertainment', keywords: 'arts show play teatro', symbol: { ios: 'theatermasks.fill', android: 'theater_comedy', web: 'theater_comedy' } },
  nightlife: { label: 'Nightlife', group: 'Entertainment', keywords: 'club party dancing rumba', symbol: { ios: 'music.mic', android: 'nightlife', web: 'nightlife' } },
  hobbies: { label: 'Hobbies', group: 'Entertainment', keywords: 'crafts art painting', symbol: { ios: 'paintpalette.fill', android: 'palette', web: 'palette' } },
  photography: { label: 'Photography', group: 'Entertainment', keywords: 'camera photos', symbol: { ios: 'camera.fill', android: 'photo_camera', web: 'photo_camera' } },
  news: { label: 'News', group: 'Entertainment', keywords: 'magazine press media', symbol: { ios: 'newspaper.fill', android: 'newspaper', web: 'newspaper' } },
  sports: { label: 'Sports', group: 'Entertainment', keywords: 'ball recreation soccer', symbol: { ios: 'soccerball', android: 'sports_soccer', web: 'sports_soccer' } },
  travel: { label: 'Travel', group: 'Travel', keywords: 'trip vacation world viaje', symbol: { ios: 'globe.americas.fill', android: 'travel_explore', web: 'travel_explore' } },
  flight: { label: 'Flights', group: 'Travel', keywords: 'plane airline airport', symbol: { ios: 'airplane', android: 'flight', web: 'flight' } },
  hotel: { label: 'Hotel', group: 'Travel', keywords: 'lodging stay accommodation', symbol: { ios: 'bed.double.fill', android: 'hotel', web: 'hotel' } },
  'car-rental': { label: 'Car rental', group: 'Travel', keywords: 'rent vehicle hire', symbol: { ios: 'car.rear.fill', android: 'car_rental', web: 'car_rental' } },
  luggage: { label: 'Luggage', group: 'Travel', keywords: 'suitcase baggage maleta', symbol: { ios: 'suitcase.fill', android: 'luggage', web: 'luggage' } },
  beach: { label: 'Beach', group: 'Travel', keywords: 'sea resort summer playa', symbol: { ios: 'beach.umbrella.fill', android: 'beach_access', web: 'beach_access' } },
  camping: { label: 'Camping', group: 'Travel', keywords: 'tent outdoors cabin', symbol: { ios: 'tent.fill', android: 'cabin', web: 'cabin' } },
  hiking: { label: 'Hiking', group: 'Travel', keywords: 'trekking mountain trail', symbol: { ios: 'figure.hiking', android: 'hiking', web: 'hiking' } },
  sightseeing: { label: 'Sightseeing', group: 'Travel', keywords: 'tour map attractions', symbol: { ios: 'map.fill', android: 'map', web: 'map' } },
  bank: { label: 'Bank', group: 'Finance', keywords: 'financial institution banco', symbol: { ios: 'building.columns.fill', android: 'account_balance', web: 'account_balance' } },
  'credit-card': { label: 'Credit card', group: 'Finance', keywords: 'payment debt tarjeta', symbol: { ios: 'creditcard.fill', android: 'credit_card', web: 'credit_card' } },
  savings: { label: 'Savings', group: 'Finance', keywords: 'piggy bank money ahorro', symbol: { ios: 'banknote.fill', android: 'savings', web: 'savings' } },
  investment: { label: 'Investment', group: 'Finance', keywords: 'stocks growth chart', symbol: { ios: 'chart.line.uptrend.xyaxis', android: 'trending_up', web: 'trending_up' } },
  crypto: { label: 'Crypto', group: 'Finance', keywords: 'bitcoin blockchain digital', symbol: { ios: 'bitcoinsign.circle.fill', android: 'currency_bitcoin', web: 'currency_bitcoin' } },
  dividends: { label: 'Dividends', group: 'Finance', keywords: 'yield returns payout', symbol: { ios: 'chart.pie.fill', android: 'pie_chart', web: 'pie_chart' } },
  loan: { label: 'Loan', group: 'Finance', keywords: 'credit borrow installment prestamo', symbol: { ios: 'building.columns.circle.fill', android: 'request_quote', web: 'request_quote' } },
  fees: { label: 'Fees', group: 'Finance', keywords: 'charges commission interest', symbol: { ios: 'percent', android: 'percent', web: 'percent' } },
  taxes: { label: 'Taxes', group: 'Finance', keywords: 'impuestos government declaration', symbol: { ios: 'doc.plaintext.fill', android: 'description', web: 'description' } },
  insurance: { label: 'Insurance', group: 'Finance', keywords: 'coverage policy seguro', symbol: { ios: 'umbrella.fill', android: 'umbrella', web: 'umbrella' } },
  atm: { label: 'Cash & ATM', group: 'Finance', keywords: 'withdrawal efectivo cajero', symbol: { ios: 'dollarsign.circle.fill', android: 'local_atm', web: 'local_atm' } },
  wallet: { label: 'Wallet', group: 'Finance', keywords: 'cash pocket money billetera', symbol: { ios: 'wallet.pass.fill', android: 'wallet', web: 'wallet' } },
  exchange: { label: 'Exchange', group: 'Finance', keywords: 'currency conversion swap fx', symbol: { ios: 'arrow.left.arrow.right', android: 'swap_horiz', web: 'swap_horiz' } },
  refund: { label: 'Refund', group: 'Finance', keywords: 'return reimbursement devolucion', symbol: { ios: 'arrow.uturn.backward.circle.fill', android: 'currency_exchange', web: 'currency_exchange' } },
  salary: { label: 'Salary', group: 'Work & income', keywords: 'paycheck wages nomina', symbol: { ios: 'banknote.fill', android: 'payments', web: 'payments' } },
  freelance: { label: 'Freelance', group: 'Work & income', keywords: 'work contract client', symbol: { ios: 'briefcase.fill', android: 'work', web: 'work' } },
  business: { label: 'Business', group: 'Work & income', keywords: 'company revenue sales', symbol: { ios: 'chart.bar.fill', android: 'bar_chart', web: 'bar_chart' } },
  office: { label: 'Office', group: 'Work & income', keywords: 'workplace coworking desk', symbol: { ios: 'building.fill', android: 'business_center', web: 'business_center' } },
  bonus: { label: 'Bonus', group: 'Work & income', keywords: 'income award prima', symbol: { ios: 'star.circle.fill', android: 'workspace_premium', web: 'workspace_premium' } },
  tips: { label: 'Tips', group: 'Work & income', keywords: 'gratuity propina extra', symbol: { ios: 'star.fill', android: 'star', web: 'star' } },
  'rental-income': { label: 'Rental income', group: 'Work & income', keywords: 'arriendo tenant property', symbol: { ios: 'key.fill', android: 'key', web: 'key' } },
  pension: { label: 'Pension', group: 'Work & income', keywords: 'retirement jubilacion', symbol: { ios: 'hourglass', android: 'hourglass_empty', web: 'hourglass_empty' } },
  family: { label: 'Family', group: 'Family & pets', keywords: 'people household familia', symbol: { ios: 'person.3.fill', android: 'family_restroom', web: 'family_restroom' } },
  friends: { label: 'Friends', group: 'Family & pets', keywords: 'social group people amigos', symbol: { ios: 'person.2.fill', android: 'group', web: 'group' } },
  childcare: { label: 'Childcare', group: 'Family & pets', keywords: 'children daycare nanny', symbol: { ios: 'figure.and.child.holdinghands', android: 'child_care', web: 'child_care' } },
  baby: { label: 'Baby', group: 'Family & pets', keywords: 'newborn stroller diapers bebe', symbol: { ios: 'stroller.fill', android: 'stroller', web: 'stroller' } },
  toys: { label: 'Toys', group: 'Family & pets', keywords: 'kids play juguetes', symbol: { ios: 'teddybear.fill', android: 'toys', web: 'toys' } },
  pets: { label: 'Pets', group: 'Family & pets', keywords: 'dog cat animal mascota', symbol: { ios: 'pawprint.fill', android: 'pets', web: 'pets' } },
  vet: { label: 'Vet', group: 'Family & pets', keywords: 'veterinary animal health', symbol: { ios: 'syringe.fill', android: 'vaccines', web: 'vaccines' } },
  gift: { label: 'Gift', group: 'Family & pets', keywords: 'present regalo', symbol: { ios: 'gift.fill', android: 'redeem', web: 'redeem' } },
  celebration: { label: 'Celebration', group: 'Family & pets', keywords: 'party birthday fiesta', symbol: { ios: 'party.popper.fill', android: 'celebration', web: 'celebration' } },
  wedding: { label: 'Wedding', group: 'Family & pets', keywords: 'marriage anniversary matrimonio', symbol: { ios: 'heart.circle.fill', android: 'favorite', web: 'favorite' } },
  charity: { label: 'Charity', group: 'Other', keywords: 'donation giving donacion', symbol: { ios: 'heart.fill', android: 'volunteer_activism', web: 'volunteer_activism' } },
  tag: { label: 'Tag', group: 'Other', keywords: 'label custom generic', symbol: { ios: 'tag.fill', android: 'sell', web: 'sell' } },
  uncategorized: { label: 'Uncategorized', group: 'Other', keywords: 'unknown pending question', symbol: { ios: 'questionmark.circle.fill', android: 'help', web: 'help' } },
  other: { label: 'Other', group: 'Other', keywords: 'miscellaneous category', symbol: { ios: 'square.grid.2x2.fill', android: 'category', web: 'category' } },
} satisfies Record<string, CategoryIconDefinition>;

export type CategoryIcon = keyof typeof categoryIconCatalog;
export const categoryIconKeys = Object.keys(categoryIconCatalog) as CategoryIcon[];
export const categoryIcons = Object.fromEntries(categoryIconKeys.map((id) => [id, categoryIconCatalog[id].symbol])) as Record<CategoryIcon, SymbolViewProps['name']>;
export const fallbackCategoryIcon: CategoryIcon = 'other';
export function isCategoryIcon(value: string): value is CategoryIcon { return Object.prototype.hasOwnProperty.call(categoryIconCatalog, value); }
export function getCategoryIcon(value: string): SymbolViewProps['name'] { return isCategoryIcon(value) ? categoryIconCatalog[value].symbol : categoryIconCatalog[fallbackCategoryIcon].symbol; }
export function searchCategoryIcons(query: string) { const normalized = query.trim().toLocaleLowerCase('en'); return categoryIconKeys.filter((id) => { const item = categoryIconCatalog[id]; return !normalized || `${id} ${item.label} ${item.group} ${item.keywords}`.toLocaleLowerCase('en').includes(normalized); }); }
