import type { SymbolViewProps } from 'expo-symbols';

export const categoryIconGroupNames = ['Food', 'Home & utilities', 'Transportation', 'Shopping', 'Health', 'Personal care', 'Education', 'Entertainment', 'Travel', 'Finance', 'Work & income', 'Family & pets', 'Other'] as const;
export type CategoryIconGroup = (typeof categoryIconGroupNames)[number];

type CategoryIconDefinition = { label: string; group: CategoryIconGroup; keywords: string; symbol: SymbolViewProps['name'] };

/**
 * Curated icon catalog. Keys are persisted on `categories.icon`, so an existing
 * key is never renamed or removed — only new ones are appended.
 *
 * Each symbol pairs an SF Symbol (iOS) with a Material Symbol (Android/web).
 * TypeScript rejects a name that does not exist on either platform. It cannot
 * reject a *newer* SF Symbol, which type-checks and then renders blank on the
 * app's iOS 16.4 minimum — `scripts/validate-category-icons.mjs` checks that, and
 * runs with `npm run test:categories`.
 */
export const categoryIconCatalog = {
  food: { label: 'Food', group: 'Food', keywords: 'meal dining', symbol: { ios: 'fork.knife', android: 'restaurant', web: 'restaurant' } },
  groceries: { label: 'Groceries', group: 'Food', keywords: 'market food basket supermarket', symbol: { ios: 'basket.fill', android: 'grocery', web: 'grocery' } },
  restaurant: { label: 'Restaurant', group: 'Food', keywords: 'dinner lunch takeout', symbol: { ios: 'takeoutbag.and.cup.and.straw.fill', android: 'local_dining', web: 'local_dining' } },
  coffee: { label: 'Coffee', group: 'Food', keywords: 'cafe drink tea', symbol: { ios: 'cup.and.saucer.fill', android: 'local_cafe', web: 'local_cafe' } },
  bar: { label: 'Bar & drinks', group: 'Food', keywords: 'alcohol wine beer', symbol: { ios: 'wineglass.fill', android: 'local_bar', web: 'local_bar' } },
  dessert: { label: 'Dessert', group: 'Food', keywords: 'sweets cake bakery ice cream', symbol: { ios: 'birthday.cake.fill', android: 'icecream', web: 'icecream' } },
  'food-delivery': { label: 'Food delivery', group: 'Food', keywords: 'takeaway courier domicilio', symbol: { ios: 'scooter', android: 'delivery_dining', web: 'delivery_dining' } },
  'fast-food': { label: 'Fast food', group: 'Food', keywords: 'burger comida rapida hamburguesa', symbol: { ios: 'takeoutbag.and.cup.and.straw', android: 'fastfood', web: 'fastfood' } },
  pizza: { label: 'Pizza', group: 'Food', keywords: 'italian pizzeria', symbol: { ios: 'fork.knife.circle', android: 'local_pizza', web: 'local_pizza' } },
  breakfast: { label: 'Breakfast', group: 'Food', keywords: 'desayuno morning eggs', symbol: { ios: 'sunrise.fill', android: 'egg_alt', web: 'egg_alt' } },
  lunch: { label: 'Lunch', group: 'Food', keywords: 'almuerzo corrientazo meal', symbol: { ios: 'fork.knife.circle.fill', android: 'lunch_dining', web: 'lunch_dining' } },
  snacks: { label: 'Snacks', group: 'Food', keywords: 'mecato chips candy', symbol: { ios: 'popcorn.fill', android: 'cookie', web: 'cookie' } },
  'fruit-vegetables': { label: 'Fruit & vegetables', group: 'Food', keywords: 'frutas verduras produce market', symbol: { ios: 'carrot.fill', android: 'nutrition', web: 'nutrition' } },
  'meat-fish': { label: 'Meat & fish', group: 'Food', keywords: 'carne pescado butcher seafood', symbol: { ios: 'fish.fill', android: 'set_meal', web: 'set_meal' } },
  wine: { label: 'Wine', group: 'Food', keywords: 'vino bottle', symbol: { ios: 'wineglass', android: 'wine_bar', web: 'wine_bar' } },
  tea: { label: 'Tea', group: 'Food', keywords: 'te infusion aromatica', symbol: { ios: 'mug.fill', android: 'emoji_food_beverage', web: 'emoji_food_beverage' } },
  cafeteria: { label: 'Cafeteria', group: 'Food', keywords: 'casino menu canteen', symbol: { ios: 'menucard.fill', android: 'restaurant_menu', web: 'restaurant_menu' } },
  bills: { label: 'Bills', group: 'Home & utilities', keywords: 'receipt utilities invoice', symbol: { ios: 'doc.text.fill', android: 'receipt_long', web: 'receipt_long' } },
  home: { label: 'Home', group: 'Home & utilities', keywords: 'house household', symbol: { ios: 'house.fill', android: 'home', web: 'home' } },
  rent: { label: 'Rent', group: 'Home & utilities', keywords: 'lease apartment arriendo', symbol: { ios: 'building.2.fill', android: 'apartment', web: 'apartment' } },
  mortgage: { label: 'Mortgage', group: 'Home & utilities', keywords: 'housing loan property hipoteca', symbol: { ios: 'house.and.flag.fill', android: 'real_estate_agent', web: 'real_estate_agent' } },
  electricity: { label: 'Electricity', group: 'Home & utilities', keywords: 'power energy light', symbol: { ios: 'bolt.fill', android: 'bolt', web: 'bolt' } },
  water: { label: 'Water', group: 'Home & utilities', keywords: 'utility drop', symbol: { ios: 'drop.fill', android: 'water_drop', web: 'water_drop' } },
  gas: { label: 'Gas', group: 'Home & utilities', keywords: 'heating utility flame', symbol: { ios: 'flame.fill', android: 'local_fire_department', web: 'local_fire_department' } },
  internet: { label: 'Internet', group: 'Home & utilities', keywords: 'wifi broadband router', symbol: { ios: 'wifi', android: 'wifi', web: 'wifi' } },
  phone: { label: 'Phone', group: 'Home & utilities', keywords: 'mobile cellular', symbol: { ios: 'iphone', android: 'smartphone', web: 'smartphone' } },
  furniture: { label: 'Furniture', group: 'Home & utilities', keywords: 'sofa chair decor', symbol: { ios: 'sofa.fill', android: 'chair', web: 'chair' } },
  appliances: { label: 'Appliances', group: 'Home & utilities', keywords: 'kitchen fridge white goods', symbol: { ios: 'refrigerator.fill', android: 'kitchen', web: 'kitchen' } },
  maintenance: { label: 'Repairs', group: 'Home & utilities', keywords: 'handyman tools fix plumbing', symbol: { ios: 'wrench.and.screwdriver.fill', android: 'handyman', web: 'handyman' } },
  cleaning: { label: 'Cleaning', group: 'Home & utilities', keywords: 'housekeeping chores aseo', symbol: { ios: 'sparkles', android: 'cleaning_services', web: 'cleaning_services' } },
  garden: { label: 'Garden', group: 'Home & utilities', keywords: 'yard plants outdoor', symbol: { ios: 'leaf.fill', android: 'yard', web: 'yard' } },
  waste: { label: 'Waste', group: 'Home & utilities', keywords: 'garbage trash recycling basura', symbol: { ios: 'trash.fill', android: 'delete', web: 'delete' } },
  'home-security': { label: 'Home security', group: 'Home & utilities', keywords: 'alarm monitoring lock', symbol: { ios: 'lock.shield.fill', android: 'security', web: 'security' } },
  bedroom: { label: 'Bedroom', group: 'Home & utilities', keywords: 'cama colchon mattress', symbol: { ios: 'bed.double', android: 'bed', web: 'bed' } },
  kitchen: { label: 'Kitchen', group: 'Home & utilities', keywords: 'cocina utensils cookware', symbol: { ios: 'cooktop.fill', android: 'countertops', web: 'countertops' } },
  lighting: { label: 'Lighting', group: 'Home & utilities', keywords: 'bombillo luz lamp', symbol: { ios: 'lightbulb.fill', android: 'lightbulb', web: 'lightbulb' } },
  'air-conditioning': { label: 'Air conditioning', group: 'Home & utilities', keywords: 'aire heating calefaccion', symbol: { ios: 'snowflake', android: 'ac_unit', web: 'ac_unit' } },
  plumbing: { label: 'Plumbing', group: 'Home & utilities', keywords: 'plomero fontanero pipes', symbol: { ios: 'drop.triangle.fill', android: 'plumbing', web: 'plumbing' } },
  painting: { label: 'Painting', group: 'Home & utilities', keywords: 'pintura walls decor', symbol: { ios: 'paintbrush.fill', android: 'format_paint', web: 'format_paint' } },
  tools: { label: 'Tools', group: 'Home & utilities', keywords: 'herramientas ferreteria construction', symbol: { ios: 'hammer.fill', android: 'construction', web: 'construction' } },
  moving: { label: 'Moving', group: 'Home & utilities', keywords: 'trasteo mudanza truck', symbol: { ios: 'box.truck.fill', android: 'local_shipping', web: 'local_shipping' } },
  storage: { label: 'Storage', group: 'Home & utilities', keywords: 'bodega deposito boxes', symbol: { ios: 'archivebox.fill', android: 'warehouse', web: 'warehouse' } },
  'condo-fees': { label: 'Condo fees', group: 'Home & utilities', keywords: 'administracion hoa building', symbol: { ios: 'building.2.crop.circle.fill', android: 'domain', web: 'domain' } },
  pool: { label: 'Pool', group: 'Home & utilities', keywords: 'piscina swimming', symbol: { ios: 'figure.pool.swim', android: 'pool', web: 'pool' } },
  'cable-tv': { label: 'Cable & satellite', group: 'Home & utilities', keywords: 'television cable antenna', symbol: { ios: 'antenna.radiowaves.left.and.right', android: 'satellite_alt', web: 'satellite_alt' } },
  transport: { label: 'Car', group: 'Transportation', keywords: 'transport vehicle drive', symbol: { ios: 'car.fill', android: 'directions_car', web: 'directions_car' } },
  bus: { label: 'Public transit', group: 'Transportation', keywords: 'bus metro transmilenio', symbol: { ios: 'bus.fill', android: 'directions_bus', web: 'directions_bus' } },
  train: { label: 'Train', group: 'Transportation', keywords: 'rail tram subway', symbol: { ios: 'tram.fill', android: 'train', web: 'train' } },
  taxi: { label: 'Taxi & rideshare', group: 'Transportation', keywords: 'uber cab didi', symbol: { ios: 'car.2.fill', android: 'local_taxi', web: 'local_taxi' } },
  bike: { label: 'Bike', group: 'Transportation', keywords: 'bicycle cycling scooter', symbol: { ios: 'bicycle', android: 'pedal_bike', web: 'pedal_bike' } },
  ferry: { label: 'Ferry', group: 'Transportation', keywords: 'boat ship water', symbol: { ios: 'ferry.fill', android: 'directions_boat', web: 'directions_boat' } },
  fuel: { label: 'Fuel', group: 'Transportation', keywords: 'gas petrol gasolina', symbol: { ios: 'fuelpump.fill', android: 'local_gas_station', web: 'local_gas_station' } },
  'ev-charging': { label: 'EV charging', group: 'Transportation', keywords: 'electric car battery', symbol: { ios: 'bolt.car.fill', android: 'electric_car', web: 'electric_car' } },
  parking: { label: 'Parking', group: 'Transportation', keywords: 'car garage', symbol: { ios: 'parkingsign.circle.fill', android: 'local_parking', web: 'local_parking' } },
  toll: { label: 'Tolls', group: 'Transportation', keywords: 'peaje highway road', symbol: { ios: 'road.lanes', android: 'toll', web: 'toll' } },
  'car-service': { label: 'Car service', group: 'Transportation', keywords: 'mechanic repair taller', symbol: { ios: 'wrench.adjustable.fill', android: 'car_repair', web: 'car_repair' } },
  motorcycle: { label: 'Motorcycle', group: 'Transportation', keywords: 'moto motocicleta', symbol: { ios: 'scooter', android: 'two_wheeler', web: 'two_wheeler' } },
  'car-wash': { label: 'Car wash', group: 'Transportation', keywords: 'lavadero lavado', symbol: { ios: 'bubbles.and.sparkles.fill', android: 'local_car_wash', web: 'local_car_wash' } },
  subway: { label: 'Subway', group: 'Transportation', keywords: 'metro underground', symbol: { ios: 'tram.fill.tunnel', android: 'subway', web: 'subway' } },
  shuttle: { label: 'Shuttle', group: 'Transportation', keywords: 'buseta van transfer airport', symbol: { ios: 'bus.doubledecker.fill', android: 'airport_shuttle', web: 'airport_shuttle' } },
  'e-scooter': { label: 'E-scooter', group: 'Transportation', keywords: 'patineta scooter rental', symbol: { ios: 'bolt.circle.fill', android: 'electric_scooter', web: 'electric_scooter' } },
  fines: { label: 'Traffic fines', group: 'Transportation', keywords: 'multas comparendo tickets', symbol: { ios: 'exclamationmark.octagon.fill', android: 'local_police', web: 'local_police' } },
  'driving-license': { label: 'Driving license', group: 'Transportation', keywords: 'licencia pase documents', symbol: { ios: 'person.text.rectangle.fill', android: 'badge', web: 'badge' } },
  'road-trip': { label: 'Road trip', group: 'Transportation', keywords: 'carretera paseo route', symbol: { ios: 'signpost.right.fill', android: 'route', web: 'route' } },
  shopping: { label: 'Shopping', group: 'Shopping', keywords: 'bag purchases', symbol: { ios: 'bag.fill', android: 'shopping_bag', web: 'shopping_bag' } },
  cart: { label: 'Shopping cart', group: 'Shopping', keywords: 'store buy', symbol: { ios: 'cart.fill', android: 'shopping_cart', web: 'shopping_cart' } },
  clothing: { label: 'Clothing', group: 'Shopping', keywords: 'fashion apparel ropa', symbol: { ios: 'tshirt.fill', android: 'checkroom', web: 'checkroom' } },
  electronics: { label: 'Electronics', group: 'Shopping', keywords: 'computer tech gadgets', symbol: { ios: 'desktopcomputer', android: 'computer', web: 'computer' } },
  'online-shopping': { label: 'Online shopping', group: 'Shopping', keywords: 'delivery parcel package envio', symbol: { ios: 'shippingbox.fill', android: 'inventory_2', web: 'inventory_2' } },
  mall: { label: 'Mall', group: 'Shopping', keywords: 'centro comercial retail store', symbol: { ios: 'bag.circle.fill', android: 'local_mall', web: 'local_mall' } },
  jewelry: { label: 'Jewelry', group: 'Shopping', keywords: 'watch accessories luxury', symbol: { ios: 'diamond.fill', android: 'diamond', web: 'diamond' } },
  watch: { label: 'Watch', group: 'Shopping', keywords: 'reloj smartwatch', symbol: { ios: 'applewatch', android: 'watch', web: 'watch' } },
  'hardware-store': { label: 'Hardware store', group: 'Shopping', keywords: 'ferreteria homecenter', symbol: { ios: 'wrench.and.screwdriver', android: 'hardware', web: 'hardware' } },
  'convenience-store': { label: 'Convenience store', group: 'Shopping', keywords: 'tienda barrio minimarket', symbol: { ios: 'cart.circle.fill', android: 'local_convenience_store', web: 'local_convenience_store' } },
  market: { label: 'Market', group: 'Shopping', keywords: 'plaza mercado local', symbol: { ios: 'basket', android: 'storefront', web: 'storefront' } },
  'second-hand': { label: 'Second-hand', group: 'Shopping', keywords: 'usado segunda mano thrift', symbol: { ios: 'arrow.3.trianglepath', android: 'recycling', web: 'recycling' } },
  headphones: { label: 'Headphones', group: 'Shopping', keywords: 'audifonos audio accessories', symbol: { ios: 'headphones', android: 'headphones', web: 'headphones' } },
  laptop: { label: 'Laptop', group: 'Shopping', keywords: 'portatil computer', symbol: { ios: 'laptopcomputer.and.iphone', android: 'laptop_mac', web: 'laptop_mac' } },
  devices: { label: 'Devices', group: 'Shopping', keywords: 'dispositivos tablet celular', symbol: { ios: 'ipad.and.iphone', android: 'devices', web: 'devices' } },
  'sporting-goods': { label: 'Sporting goods', group: 'Shopping', keywords: 'deportes equipment', symbol: { ios: 'tennis.racket', android: 'sports_tennis', web: 'sports_tennis' } },
  health: { label: 'Health', group: 'Health', keywords: 'medical care salud', symbol: { ios: 'cross.case.fill', android: 'medical_services', web: 'medical_services' } },
  doctor: { label: 'Doctor', group: 'Health', keywords: 'clinic hospital consultation', symbol: { ios: 'stethoscope', android: 'local_hospital', web: 'local_hospital' } },
  pharmacy: { label: 'Pharmacy', group: 'Health', keywords: 'medicine prescription drugs', symbol: { ios: 'pills.fill', android: 'medication', web: 'medication' } },
  lab: { label: 'Lab tests', group: 'Health', keywords: 'exams bloodwork analysis', symbol: { ios: 'cross.vial.fill', android: 'science', web: 'science' } },
  dental: { label: 'Dental', group: 'Health', keywords: 'dentist teeth', symbol: { ios: 'mouth.fill', android: 'dentistry', web: 'dentistry' } },
  vision: { label: 'Vision', group: 'Health', keywords: 'glasses optical eyes', symbol: { ios: 'eyeglasses', android: 'visibility', web: 'visibility' } },
  therapy: { label: 'Therapy', group: 'Health', keywords: 'mental health psychology counseling', symbol: { ios: 'brain.head.profile', android: 'psychology', web: 'psychology' } },
  fitness: { label: 'Fitness', group: 'Health', keywords: 'gym exercise weights', symbol: { ios: 'dumbbell.fill', android: 'fitness_center', web: 'fitness_center' } },
  hospital: { label: 'Hospital', group: 'Health', keywords: 'urgencias emergency clinica', symbol: { ios: 'cross.fill', android: 'emergency', web: 'emergency' } },
  physiotherapy: { label: 'Physiotherapy', group: 'Health', keywords: 'fisioterapia rehab', symbol: { ios: 'figure.roll', android: 'accessible', web: 'accessible' } },
  'health-insurance': { label: 'Health insurance', group: 'Health', keywords: 'eps prepagada medicina', symbol: { ios: 'heart.text.square.fill', android: 'health_and_safety', web: 'health_and_safety' } },
  'heart-health': { label: 'Checkup', group: 'Health', keywords: 'chequeo cardiology exam', symbol: { ios: 'waveform.path.ecg', android: 'monitor_heart', web: 'monitor_heart' } },
  hearing: { label: 'Hearing', group: 'Health', keywords: 'audiologia ears', symbol: { ios: 'ear.fill', android: 'hearing', web: 'hearing' } },
  supplements: { label: 'Supplements', group: 'Health', keywords: 'vitaminas suplementos', symbol: { ios: 'pills', android: 'medication_liquid', web: 'medication_liquid' } },
  yoga: { label: 'Yoga', group: 'Health', keywords: 'meditation pilates', symbol: { ios: 'figure.yoga', android: 'self_improvement', web: 'self_improvement' } },
  running: { label: 'Running', group: 'Health', keywords: 'correr trote marathon', symbol: { ios: 'figure.run', android: 'directions_run', web: 'directions_run' } },
  'martial-arts': { label: 'Martial arts', group: 'Health', keywords: 'artes marciales karate boxing', symbol: { ios: 'figure.martial.arts', android: 'sports_martial_arts', web: 'sports_martial_arts' } },
  haircut: { label: 'Haircut', group: 'Personal care', keywords: 'barber salon hair peluqueria', symbol: { ios: 'scissors', android: 'content_cut', web: 'content_cut' } },
  beauty: { label: 'Beauty', group: 'Personal care', keywords: 'cosmetics makeup skincare', symbol: { ios: 'comb.fill', android: 'face', web: 'face' } },
  spa: { label: 'Spa & wellness', group: 'Personal care', keywords: 'massage relax yoga', symbol: { ios: 'figure.mind.and.body', android: 'spa', web: 'spa' } },
  laundry: { label: 'Laundry', group: 'Personal care', keywords: 'dry cleaning washing lavanderia', symbol: { ios: 'washer.fill', android: 'local_laundry_service', web: 'local_laundry_service' } },
  hygiene: { label: 'Hygiene', group: 'Personal care', keywords: 'aseo personal soap', symbol: { ios: 'hands.sparkles.fill', android: 'soap', web: 'soap' } },
  shower: { label: 'Toiletries', group: 'Personal care', keywords: 'bano ducha shampoo', symbol: { ios: 'shower.fill', android: 'shower', web: 'shower' } },
  makeup: { label: 'Makeup', group: 'Personal care', keywords: 'maquillaje cosmetics', symbol: { ios: 'paintbrush.pointed.fill', android: 'face_retouching_natural', web: 'face_retouching_natural' } },
  tailor: { label: 'Tailor', group: 'Personal care', keywords: 'modista sastre arreglos', symbol: { ios: 'tshirt', android: 'dry_cleaning', web: 'dry_cleaning' } },
  education: { label: 'Education', group: 'Education', keywords: 'school study', symbol: { ios: 'graduationcap.fill', android: 'school', web: 'school' } },
  tuition: { label: 'Tuition', group: 'Education', keywords: 'university fees semester matricula', symbol: { ios: 'graduationcap.circle.fill', android: 'cast_for_education', web: 'cast_for_education' } },
  books: { label: 'Books', group: 'Education', keywords: 'reading library', symbol: { ios: 'books.vertical.fill', android: 'menu_book', web: 'menu_book' } },
  courses: { label: 'Courses', group: 'Education', keywords: 'online training workshop', symbol: { ios: 'laptopcomputer', android: 'co_present', web: 'co_present' } },
  'school-supplies': { label: 'School supplies', group: 'Education', keywords: 'stationery backpack materials utiles', symbol: { ios: 'backpack.fill', android: 'backpack', web: 'backpack' } },
  languages: { label: 'Languages', group: 'Education', keywords: 'idiomas ingles clases', symbol: { ios: 'character.book.closed.fill', android: 'translate', web: 'translate' } },
  'music-lessons': { label: 'Music lessons', group: 'Education', keywords: 'clases musica piano', symbol: { ios: 'pianokeys', android: 'piano', web: 'piano' } },
  certification: { label: 'Certification', group: 'Education', keywords: 'certificado exam diploma', symbol: { ios: 'checkmark.seal.fill', android: 'verified', web: 'verified' } },
  library: { label: 'Library', group: 'Education', keywords: 'biblioteca membership', symbol: { ios: 'books.vertical', android: 'local_library', web: 'local_library' } },
  stationery: { label: 'Stationery', group: 'Education', keywords: 'papeleria cuadernos notebooks', symbol: { ios: 'pencil.and.ruler.fill', android: 'edit_note', web: 'edit_note' } },
  scholarship: { label: 'Scholarship', group: 'Education', keywords: 'beca grant award', symbol: { ios: 'rosette', android: 'military_tech', web: 'military_tech' } },
  entertainment: { label: 'Games', group: 'Entertainment', keywords: 'gaming fun console', symbol: { ios: 'gamecontroller.fill', android: 'sports_esports', web: 'sports_esports' } },
  movies: { label: 'Movies', group: 'Entertainment', keywords: 'cinema film', symbol: { ios: 'film.fill', android: 'movie', web: 'movie' } },
  streaming: { label: 'Streaming', group: 'Entertainment', keywords: 'netflix spotify video', symbol: { ios: 'play.rectangle.fill', android: 'subscriptions', web: 'subscriptions' } },
  subscriptions: { label: 'Subscriptions', group: 'Entertainment', keywords: 'recurring membership renewal', symbol: { ios: 'arrow.triangle.2.circlepath', android: 'autorenew', web: 'autorenew' } },
  tv: { label: 'TV', group: 'Entertainment', keywords: 'television cable', symbol: { ios: 'tv.fill', android: 'tv', web: 'tv' } },
  music: { label: 'Music', group: 'Entertainment', keywords: 'audio songs', symbol: { ios: 'music.note', android: 'music_note', web: 'music_note' } },
  concerts: { label: 'Concerts', group: 'Entertainment', keywords: 'tickets events live boletas', symbol: { ios: 'ticket.fill', android: 'local_activity', web: 'local_activity' } },
  theater: { label: 'Theater', group: 'Entertainment', keywords: 'arts show play teatro', symbol: { ios: 'theatermasks.fill', android: 'theater_comedy', web: 'theater_comedy' } },
  nightlife: { label: 'Nightlife', group: 'Entertainment', keywords: 'club party dancing rumba', symbol: { ios: 'music.mic', android: 'nightlife', web: 'nightlife' } },
  hobbies: { label: 'Hobbies', group: 'Entertainment', keywords: 'crafts art painting', symbol: { ios: 'paintpalette.fill', android: 'palette', web: 'palette' } },
  photography: { label: 'Photography', group: 'Entertainment', keywords: 'camera photos', symbol: { ios: 'camera.fill', android: 'photo_camera', web: 'photo_camera' } },
  news: { label: 'News', group: 'Entertainment', keywords: 'magazine press media', symbol: { ios: 'newspaper.fill', android: 'newspaper', web: 'newspaper' } },
  sports: { label: 'Sports', group: 'Entertainment', keywords: 'ball recreation soccer', symbol: { ios: 'soccerball', android: 'sports_soccer', web: 'sports_soccer' } },
  'board-games': { label: 'Board games', group: 'Entertainment', keywords: 'juegos de mesa dice', symbol: { ios: 'dice.fill', android: 'casino', web: 'casino' } },
  museum: { label: 'Museum', group: 'Entertainment', keywords: 'museo exhibition culture', symbol: { ios: 'building.columns.circle', android: 'museum', web: 'museum' } },
  'amusement-park': { label: 'Amusement park', group: 'Entertainment', keywords: 'parque diversiones rides', symbol: { ios: 'balloon.2.fill', android: 'attractions', web: 'attractions' } },
  podcasts: { label: 'Podcasts', group: 'Entertainment', keywords: 'audio shows', symbol: { ios: 'mic.fill', android: 'podcasts', web: 'podcasts' } },
  apps: { label: 'Apps & software', group: 'Entertainment', keywords: 'aplicaciones software licenses', symbol: { ios: 'app.badge.fill', android: 'apps', web: 'apps' } },
  'cloud-storage': { label: 'Cloud storage', group: 'Entertainment', keywords: 'nube icloud drive backup', symbol: { ios: 'icloud.fill', android: 'cloud', web: 'cloud' } },
  golf: { label: 'Golf', group: 'Entertainment', keywords: 'club course', symbol: { ios: 'figure.golf', android: 'sports_golf', web: 'sports_golf' } },
  basketball: { label: 'Basketball', group: 'Entertainment', keywords: 'baloncesto', symbol: { ios: 'basketball.fill', android: 'sports_basketball', web: 'sports_basketball' } },
  fishing: { label: 'Fishing', group: 'Entertainment', keywords: 'pesca', symbol: { ios: 'fish', android: 'phishing', web: 'phishing' } },
  drawing: { label: 'Drawing', group: 'Entertainment', keywords: 'dibujo illustration art', symbol: { ios: 'pencil.tip', android: 'draw', web: 'draw' } },
  lottery: { label: 'Lottery', group: 'Entertainment', keywords: 'loteria chance apuestas betting', symbol: { ios: 'suit.club.fill', android: 'confirmation_number', web: 'confirmation_number' } },
  travel: { label: 'Travel', group: 'Travel', keywords: 'trip vacation world viaje', symbol: { ios: 'globe.americas.fill', android: 'travel_explore', web: 'travel_explore' } },
  flight: { label: 'Flights', group: 'Travel', keywords: 'plane airline airport', symbol: { ios: 'airplane', android: 'flight', web: 'flight' } },
  hotel: { label: 'Hotel', group: 'Travel', keywords: 'lodging stay accommodation', symbol: { ios: 'bed.double.fill', android: 'hotel', web: 'hotel' } },
  'car-rental': { label: 'Car rental', group: 'Travel', keywords: 'rent vehicle hire', symbol: { ios: 'car.rear.fill', android: 'car_rental', web: 'car_rental' } },
  luggage: { label: 'Luggage', group: 'Travel', keywords: 'suitcase baggage maleta', symbol: { ios: 'suitcase.fill', android: 'luggage', web: 'luggage' } },
  beach: { label: 'Beach', group: 'Travel', keywords: 'sea resort summer playa', symbol: { ios: 'beach.umbrella.fill', android: 'beach_access', web: 'beach_access' } },
  camping: { label: 'Camping', group: 'Travel', keywords: 'tent outdoors cabin', symbol: { ios: 'tent.fill', android: 'cabin', web: 'cabin' } },
  hiking: { label: 'Hiking', group: 'Travel', keywords: 'trekking mountain trail', symbol: { ios: 'figure.hiking', android: 'hiking', web: 'hiking' } },
  sightseeing: { label: 'Sightseeing', group: 'Travel', keywords: 'tour map attractions', symbol: { ios: 'map.fill', android: 'map', web: 'map' } },
  visa: { label: 'Visa & passport', group: 'Travel', keywords: 'pasaporte documentos embassy', symbol: { ios: 'airplane.circle.fill', android: 'airplane_ticket', web: 'airplane_ticket' } },
  cruise: { label: 'Cruise', group: 'Travel', keywords: 'crucero ship', symbol: { ios: 'ferry', android: 'directions_boat_filled', web: 'directions_boat_filled' } },
  'vacation-rental': { label: 'Vacation rental', group: 'Travel', keywords: 'airbnb finca cabana', symbol: { ios: 'house.lodge.fill', android: 'cottage', web: 'cottage' } },
  mountains: { label: 'Mountains', group: 'Travel', keywords: 'montana nature landscape', symbol: { ios: 'mountain.2.fill', android: 'landscape', web: 'landscape' } },
  ski: { label: 'Ski', group: 'Travel', keywords: 'snow esqui winter', symbol: { ios: 'figure.skiing.downhill', android: 'downhill_skiing', web: 'downhill_skiing' } },
  bank: { label: 'Bank', group: 'Finance', keywords: 'financial institution banco', symbol: { ios: 'building.columns.fill', android: 'account_balance', web: 'account_balance' } },
  'credit-card': { label: 'Credit card', group: 'Finance', keywords: 'payment debt tarjeta', symbol: { ios: 'creditcard.fill', android: 'credit_card', web: 'credit_card' } },
  savings: { label: 'Savings', group: 'Finance', keywords: 'piggy bank money ahorro', symbol: { ios: 'banknote.fill', android: 'savings', web: 'savings' } },
  investment: { label: 'Investment', group: 'Finance', keywords: 'stocks growth chart', symbol: { ios: 'chart.line.uptrend.xyaxis', android: 'trending_up', web: 'trending_up' } },
  crypto: { label: 'Crypto', group: 'Finance', keywords: 'bitcoin blockchain digital', symbol: { ios: 'bitcoinsign.circle.fill', android: 'currency_bitcoin', web: 'currency_bitcoin' } },
  dividends: { label: 'Dividends', group: 'Finance', keywords: 'yield returns payout', symbol: { ios: 'chart.pie.fill', android: 'pie_chart', web: 'pie_chart' } },
  loan: { label: 'Loan', group: 'Finance', keywords: 'credit borrow installment prestamo', symbol: { ios: 'building.columns.circle.fill', android: 'request_quote', web: 'request_quote' } },
  fees: { label: 'Fees', group: 'Finance', keywords: 'charges commission interest', symbol: { ios: 'percent', android: 'percent', web: 'percent' } },
  taxes: { label: 'Taxes', group: 'Finance', keywords: 'impuestos government declaration', symbol: { ios: 'doc.plaintext.fill', android: 'description', web: 'description' } },
  insurance: { label: 'Insurance', group: 'Finance', keywords: 'coverage policy seguro', symbol: { ios: 'umbrella.fill', android: 'umbrella', web: 'umbrella' } },
  atm: { label: 'Cash & ATM', group: 'Finance', keywords: 'withdrawal efectivo cajero', symbol: { ios: 'dollarsign.circle.fill', android: 'local_atm', web: 'local_atm' } },
  wallet: { label: 'Wallet', group: 'Finance', keywords: 'cash pocket money billetera', symbol: { ios: 'wallet.pass.fill', android: 'wallet', web: 'wallet' } },
  exchange: { label: 'Exchange', group: 'Finance', keywords: 'currency conversion swap fx', symbol: { ios: 'arrow.left.arrow.right', android: 'swap_horiz', web: 'swap_horiz' } },
  refund: { label: 'Refund', group: 'Finance', keywords: 'return reimbursement devolucion', symbol: { ios: 'arrow.uturn.backward.circle.fill', android: 'currency_exchange', web: 'currency_exchange' } },
  'emergency-fund': { label: 'Emergency fund', group: 'Finance', keywords: 'fondo emergencia reserve', symbol: { ios: 'shield.fill', android: 'shield', web: 'shield' } },
  'debt-payment': { label: 'Debt payment', group: 'Finance', keywords: 'deuda abono cuota', symbol: { ios: 'minus.circle.fill', android: 'money_off', web: 'money_off' } },
  budget: { label: 'Budget', group: 'Finance', keywords: 'presupuesto plan', symbol: { ios: 'chart.pie', android: 'account_balance_wallet', web: 'account_balance_wallet' } },
  cash: { label: 'Cash', group: 'Finance', keywords: 'efectivo billetes coins', symbol: { ios: 'dollarsign.square.fill', android: 'paid', web: 'paid' } },
  'stock-market': { label: 'Stock market', group: 'Finance', keywords: 'bolsa acciones trading', symbol: { ios: 'chart.bar.xaxis', android: 'candlestick_chart', web: 'candlestick_chart' } },
  accounting: { label: 'Accounting', group: 'Finance', keywords: 'contador contabilidad calculator', symbol: { ios: 'plus.forwardslash.minus', android: 'calculate', web: 'calculate' } },
  legal: { label: 'Legal', group: 'Finance', keywords: 'abogado notaria lawyer', symbol: { ios: 'doc.text.magnifyingglass', android: 'gavel', web: 'gavel' } },
  'credit-score': { label: 'Credit score', group: 'Finance', keywords: 'datacredito historial rating', symbol: { ios: 'gauge', android: 'speed', web: 'speed' } },
  salary: { label: 'Salary', group: 'Work & income', keywords: 'paycheck wages nomina', symbol: { ios: 'banknote.fill', android: 'payments', web: 'payments' } },
  freelance: { label: 'Freelance', group: 'Work & income', keywords: 'work contract client', symbol: { ios: 'briefcase.fill', android: 'work', web: 'work' } },
  business: { label: 'Business', group: 'Work & income', keywords: 'company revenue sales', symbol: { ios: 'chart.bar.fill', android: 'bar_chart', web: 'bar_chart' } },
  office: { label: 'Office', group: 'Work & income', keywords: 'workplace coworking desk', symbol: { ios: 'building.fill', android: 'business_center', web: 'business_center' } },
  bonus: { label: 'Bonus', group: 'Work & income', keywords: 'income award prima', symbol: { ios: 'star.circle.fill', android: 'workspace_premium', web: 'workspace_premium' } },
  tips: { label: 'Tips', group: 'Work & income', keywords: 'gratuity propina extra', symbol: { ios: 'star.fill', android: 'star', web: 'star' } },
  'rental-income': { label: 'Rental income', group: 'Work & income', keywords: 'arriendo tenant property', symbol: { ios: 'key.fill', android: 'key', web: 'key' } },
  pension: { label: 'Pension', group: 'Work & income', keywords: 'retirement jubilacion', symbol: { ios: 'hourglass', android: 'hourglass_empty', web: 'hourglass_empty' } },
  commission: { label: 'Commission', group: 'Work & income', keywords: 'comision ventas deal', symbol: { ios: 'arrow.left.arrow.right.circle.fill', android: 'handshake', web: 'handshake' } },
  consulting: { label: 'Consulting', group: 'Work & income', keywords: 'consultoria asesoria services', symbol: { ios: 'person.crop.circle.badge.checkmark', android: 'support_agent', web: 'support_agent' } },
  royalties: { label: 'Royalties', group: 'Work & income', keywords: 'regalias licensing copyright', symbol: { ios: 'c.circle.fill', android: 'copyright', web: 'copyright' } },
  selling: { label: 'Selling items', group: 'Work & income', keywords: 'venta marketplace resale', symbol: { ios: 'tag.circle.fill', android: 'local_offer', web: 'local_offer' } },
  cashback: { label: 'Cashback', group: 'Work & income', keywords: 'puntos rewards reembolso', symbol: { ios: 'giftcard.fill', android: 'card_giftcard', web: 'card_giftcard' } },
  'remote-work': { label: 'Remote work', group: 'Work & income', keywords: 'teletrabajo home office', symbol: { ios: 'house.and.flag', android: 'home_work', web: 'home_work' } },
  family: { label: 'Family', group: 'Family & pets', keywords: 'people household familia', symbol: { ios: 'person.3.fill', android: 'family_restroom', web: 'family_restroom' } },
  friends: { label: 'Friends', group: 'Family & pets', keywords: 'social group people amigos', symbol: { ios: 'person.2.fill', android: 'group', web: 'group' } },
  childcare: { label: 'Childcare', group: 'Family & pets', keywords: 'children daycare nanny', symbol: { ios: 'figure.and.child.holdinghands', android: 'child_care', web: 'child_care' } },
  baby: { label: 'Baby', group: 'Family & pets', keywords: 'newborn stroller diapers bebe', symbol: { ios: 'stroller.fill', android: 'stroller', web: 'stroller' } },
  toys: { label: 'Toys', group: 'Family & pets', keywords: 'kids play juguetes', symbol: { ios: 'teddybear.fill', android: 'toys', web: 'toys' } },
  pets: { label: 'Pets', group: 'Family & pets', keywords: 'dog cat animal mascota', symbol: { ios: 'pawprint.fill', android: 'pets', web: 'pets' } },
  vet: { label: 'Vet', group: 'Family & pets', keywords: 'veterinary animal health', symbol: { ios: 'syringe.fill', android: 'vaccines', web: 'vaccines' } },
  gift: { label: 'Gift', group: 'Family & pets', keywords: 'present regalo', symbol: { ios: 'gift.fill', android: 'redeem', web: 'redeem' } },
  celebration: { label: 'Celebration', group: 'Family & pets', keywords: 'party birthday fiesta', symbol: { ios: 'party.popper.fill', android: 'celebration', web: 'celebration' } },
  wedding: { label: 'Wedding', group: 'Family & pets', keywords: 'marriage anniversary matrimonio', symbol: { ios: 'heart.circle.fill', android: 'favorite', web: 'favorite' } },
  'elderly-care': { label: 'Elderly care', group: 'Family & pets', keywords: 'adulto mayor abuelos parents', symbol: { ios: 'figure.walk', android: 'elderly', web: 'elderly' } },
  'kids-activities': { label: 'Kids activities', group: 'Family & pets', keywords: 'actividades ninos extracurricular', symbol: { ios: 'figure.and.child.holdinghands', android: 'sports_handball', web: 'sports_handball' } },
  birthday: { label: 'Birthday', group: 'Family & pets', keywords: 'cumpleanos cake', symbol: { ios: 'birthday.cake', android: 'cake', web: 'cake' } },
  holidays: { label: 'Holidays', group: 'Family & pets', keywords: 'navidad christmas fiestas', symbol: { ios: 'gift.circle.fill', android: 'festival', web: 'festival' } },
  religious: { label: 'Religious', group: 'Family & pets', keywords: 'iglesia diezmo tithe church', symbol: { ios: 'heart.circle', android: 'church', web: 'church' } },
  charity: { label: 'Charity', group: 'Other', keywords: 'donation giving donacion', symbol: { ios: 'heart.fill', android: 'volunteer_activism', web: 'volunteer_activism' } },
  tag: { label: 'Tag', group: 'Other', keywords: 'label custom generic', symbol: { ios: 'tag.fill', android: 'sell', web: 'sell' } },
  uncategorized: { label: 'Uncategorized', group: 'Other', keywords: 'unknown pending question', symbol: { ios: 'questionmark.circle.fill', android: 'help', web: 'help' } },
  other: { label: 'Other', group: 'Other', keywords: 'miscellaneous category', symbol: { ios: 'square.grid.2x2.fill', android: 'category', web: 'category' } },
  personal: { label: 'Personal', group: 'Other', keywords: 'yo gastos personales', symbol: { ios: 'person.fill', android: 'person', web: 'person' } },
  emergency: { label: 'Emergency', group: 'Other', keywords: 'imprevisto urgente unexpected', symbol: { ios: 'exclamationmark.triangle.fill', android: 'warning', web: 'warning' } },
  favorite: { label: 'Favorite', group: 'Other', keywords: 'bookmark saved', symbol: { ios: 'bookmark.fill', android: 'bookmark', web: 'bookmark' } },
  flag: { label: 'Flag', group: 'Other', keywords: 'marker goal meta', symbol: { ios: 'flag.fill', android: 'flag', web: 'flag' } },
  private: { label: 'Private', group: 'Other', keywords: 'privado lock secret', symbol: { ios: 'lock.fill', android: 'lock', web: 'lock' } },
  annual: { label: 'Annual', group: 'Other', keywords: 'anual yearly calendar', symbol: { ios: 'calendar', android: 'calendar_month', web: 'calendar_month' } },
  installments: { label: 'Installments', group: 'Other', keywords: 'cuotas plazos schedule', symbol: { ios: 'clock.fill', android: 'schedule', web: 'schedule' } },
  alerts: { label: 'Reminders', group: 'Other', keywords: 'recordatorio notification', symbol: { ios: 'bell.fill', android: 'notifications', web: 'notifications' } },
  location: { label: 'Location', group: 'Other', keywords: 'lugar ubicacion place', symbol: { ios: 'mappin.circle.fill', android: 'location_on', web: 'location_on' } },
} satisfies Record<string, CategoryIconDefinition>;

export type CategoryIcon = keyof typeof categoryIconCatalog;
export const categoryIconKeys = Object.keys(categoryIconCatalog) as CategoryIcon[];
export const fallbackCategoryIcon: CategoryIcon = 'other';
export function isCategoryIcon(value: string): value is CategoryIcon { return Object.prototype.hasOwnProperty.call(categoryIconCatalog, value); }
export function getCategoryIcon(value: string): SymbolViewProps['name'] { return isCategoryIcon(value) ? categoryIconCatalog[value].symbol : categoryIconCatalog[fallbackCategoryIcon].symbol; }
export function searchCategoryIcons(query: string) { const normalized = query.trim().toLocaleLowerCase('en'); return categoryIconKeys.filter((id) => { const item = categoryIconCatalog[id]; return !normalized || `${id} ${item.label} ${item.group} ${item.keywords}`.toLocaleLowerCase('en').includes(normalized); }); }
