import type { SymbolViewProps } from 'expo-symbols';

import type { Language } from '@/i18n/languages';
import { getLanguage, getMessagesFor } from '@/i18n/messages';
import { foldForSearch } from '@/utils/text-search';

/** Picker groups, in display order. Titles live in the `categories.iconGroups` catalog. */
export const categoryIconGroupNames = ['food', 'home', 'transportation', 'shopping', 'health', 'personalCare', 'education', 'entertainment', 'travel', 'finance', 'work', 'family', 'other'] as const;
export type CategoryIconGroup = (typeof categoryIconGroupNames)[number];

/**
 * `keywords` are extra search terms in English and Colombian Spanish. Labels are
 * not stored here: they live in the `categories.icons` catalog, keyed by icon key.
 */
type CategoryIconDefinition = { group: CategoryIconGroup; keywords: string; symbol: SymbolViewProps['name'] };

/**
 * Curated icon catalog. Keys are persisted on `categories.icon`, so an existing
 * key is never renamed or removed — only new ones are appended.
 *
 * Each symbol pairs an SF Symbol (iOS) with a Material Symbol (Android/web).
 * TypeScript rejects a name that does not exist on either platform. It cannot
 * reject a *newer* SF Symbol, which type-checks and then renders blank on the
 * app's iOS 16.4 minimum — `scripts/validate-category-icons.mjs` checks that, and
 * runs with `npm run test:categories`.
 */
export const categoryIconCatalog = {
  food: { group: 'food', keywords: 'meal dining', symbol: { ios: 'fork.knife', android: 'restaurant', web: 'restaurant' } },
  groceries: { group: 'food', keywords: 'market food basket supermarket', symbol: { ios: 'basket.fill', android: 'grocery', web: 'grocery' } },
  restaurant: { group: 'food', keywords: 'dinner lunch takeout', symbol: { ios: 'takeoutbag.and.cup.and.straw.fill', android: 'local_dining', web: 'local_dining' } },
  coffee: { group: 'food', keywords: 'cafe drink tea', symbol: { ios: 'cup.and.saucer.fill', android: 'local_cafe', web: 'local_cafe' } },
  bar: { group: 'food', keywords: 'alcohol wine beer', symbol: { ios: 'wineglass.fill', android: 'local_bar', web: 'local_bar' } },
  dessert: { group: 'food', keywords: 'sweets cake bakery ice cream', symbol: { ios: 'birthday.cake.fill', android: 'icecream', web: 'icecream' } },
  'food-delivery': { group: 'food', keywords: 'takeaway courier domicilio', symbol: { ios: 'scooter', android: 'delivery_dining', web: 'delivery_dining' } },
  'fast-food': { group: 'food', keywords: 'burger comida rapida hamburguesa', symbol: { ios: 'takeoutbag.and.cup.and.straw', android: 'fastfood', web: 'fastfood' } },
  pizza: { group: 'food', keywords: 'italian pizzeria', symbol: { ios: 'fork.knife.circle', android: 'local_pizza', web: 'local_pizza' } },
  breakfast: { group: 'food', keywords: 'desayuno morning eggs', symbol: { ios: 'sunrise.fill', android: 'egg_alt', web: 'egg_alt' } },
  lunch: { group: 'food', keywords: 'almuerzo corrientazo meal', symbol: { ios: 'fork.knife.circle.fill', android: 'lunch_dining', web: 'lunch_dining' } },
  snacks: { group: 'food', keywords: 'mecato chips candy', symbol: { ios: 'popcorn.fill', android: 'cookie', web: 'cookie' } },
  'fruit-vegetables': { group: 'food', keywords: 'frutas verduras produce market', symbol: { ios: 'carrot.fill', android: 'nutrition', web: 'nutrition' } },
  'meat-fish': { group: 'food', keywords: 'carne pescado butcher seafood', symbol: { ios: 'fish.fill', android: 'set_meal', web: 'set_meal' } },
  wine: { group: 'food', keywords: 'vino bottle', symbol: { ios: 'wineglass', android: 'wine_bar', web: 'wine_bar' } },
  tea: { group: 'food', keywords: 'te infusion aromatica', symbol: { ios: 'mug.fill', android: 'emoji_food_beverage', web: 'emoji_food_beverage' } },
  cafeteria: { group: 'food', keywords: 'casino menu canteen', symbol: { ios: 'menucard.fill', android: 'restaurant_menu', web: 'restaurant_menu' } },
  bills: { group: 'home', keywords: 'receipt utilities invoice', symbol: { ios: 'doc.text.fill', android: 'receipt_long', web: 'receipt_long' } },
  home: { group: 'home', keywords: 'house household', symbol: { ios: 'house.fill', android: 'home', web: 'home' } },
  rent: { group: 'home', keywords: 'lease apartment arriendo', symbol: { ios: 'building.2.fill', android: 'apartment', web: 'apartment' } },
  mortgage: { group: 'home', keywords: 'housing loan property hipoteca', symbol: { ios: 'house.and.flag.fill', android: 'real_estate_agent', web: 'real_estate_agent' } },
  electricity: { group: 'home', keywords: 'power energy light', symbol: { ios: 'bolt.fill', android: 'bolt', web: 'bolt' } },
  water: { group: 'home', keywords: 'utility drop', symbol: { ios: 'drop.fill', android: 'water_drop', web: 'water_drop' } },
  gas: { group: 'home', keywords: 'heating utility flame', symbol: { ios: 'flame.fill', android: 'local_fire_department', web: 'local_fire_department' } },
  internet: { group: 'home', keywords: 'wifi broadband router', symbol: { ios: 'wifi', android: 'wifi', web: 'wifi' } },
  phone: { group: 'home', keywords: 'mobile cellular', symbol: { ios: 'iphone', android: 'smartphone', web: 'smartphone' } },
  furniture: { group: 'home', keywords: 'sofa chair decor', symbol: { ios: 'sofa.fill', android: 'chair', web: 'chair' } },
  appliances: { group: 'home', keywords: 'kitchen fridge white goods', symbol: { ios: 'refrigerator.fill', android: 'kitchen', web: 'kitchen' } },
  maintenance: { group: 'home', keywords: 'handyman tools fix plumbing', symbol: { ios: 'wrench.and.screwdriver.fill', android: 'handyman', web: 'handyman' } },
  cleaning: { group: 'home', keywords: 'housekeeping chores aseo', symbol: { ios: 'sparkles', android: 'cleaning_services', web: 'cleaning_services' } },
  garden: { group: 'home', keywords: 'yard plants outdoor', symbol: { ios: 'leaf.fill', android: 'yard', web: 'yard' } },
  waste: { group: 'home', keywords: 'garbage trash recycling basura', symbol: { ios: 'trash.fill', android: 'delete', web: 'delete' } },
  'home-security': { group: 'home', keywords: 'alarm monitoring lock', symbol: { ios: 'lock.shield.fill', android: 'security', web: 'security' } },
  bedroom: { group: 'home', keywords: 'cama colchon mattress', symbol: { ios: 'bed.double', android: 'bed', web: 'bed' } },
  kitchen: { group: 'home', keywords: 'cocina utensils cookware', symbol: { ios: 'cooktop.fill', android: 'countertops', web: 'countertops' } },
  lighting: { group: 'home', keywords: 'bombillo luz lamp', symbol: { ios: 'lightbulb.fill', android: 'lightbulb', web: 'lightbulb' } },
  'air-conditioning': { group: 'home', keywords: 'aire heating calefaccion', symbol: { ios: 'snowflake', android: 'ac_unit', web: 'ac_unit' } },
  plumbing: { group: 'home', keywords: 'plomero fontanero pipes', symbol: { ios: 'drop.triangle.fill', android: 'plumbing', web: 'plumbing' } },
  painting: { group: 'home', keywords: 'pintura walls decor', symbol: { ios: 'paintbrush.fill', android: 'format_paint', web: 'format_paint' } },
  tools: { group: 'home', keywords: 'herramientas ferreteria construction', symbol: { ios: 'hammer.fill', android: 'construction', web: 'construction' } },
  moving: { group: 'home', keywords: 'trasteo mudanza truck', symbol: { ios: 'box.truck.fill', android: 'local_shipping', web: 'local_shipping' } },
  storage: { group: 'home', keywords: 'bodega deposito boxes', symbol: { ios: 'archivebox.fill', android: 'warehouse', web: 'warehouse' } },
  'condo-fees': { group: 'home', keywords: 'administracion hoa building', symbol: { ios: 'building.2.crop.circle.fill', android: 'domain', web: 'domain' } },
  pool: { group: 'home', keywords: 'piscina swimming', symbol: { ios: 'figure.pool.swim', android: 'pool', web: 'pool' } },
  'cable-tv': { group: 'home', keywords: 'television cable antenna', symbol: { ios: 'antenna.radiowaves.left.and.right', android: 'satellite_alt', web: 'satellite_alt' } },
  transport: { group: 'transportation', keywords: 'transport vehicle drive', symbol: { ios: 'car.fill', android: 'directions_car', web: 'directions_car' } },
  bus: { group: 'transportation', keywords: 'bus metro transmilenio', symbol: { ios: 'bus.fill', android: 'directions_bus', web: 'directions_bus' } },
  train: { group: 'transportation', keywords: 'rail tram subway', symbol: { ios: 'tram.fill', android: 'train', web: 'train' } },
  taxi: { group: 'transportation', keywords: 'uber cab didi', symbol: { ios: 'car.2.fill', android: 'local_taxi', web: 'local_taxi' } },
  bike: { group: 'transportation', keywords: 'bicycle cycling scooter', symbol: { ios: 'bicycle', android: 'pedal_bike', web: 'pedal_bike' } },
  ferry: { group: 'transportation', keywords: 'boat ship water', symbol: { ios: 'ferry.fill', android: 'directions_boat', web: 'directions_boat' } },
  fuel: { group: 'transportation', keywords: 'gas petrol gasolina', symbol: { ios: 'fuelpump.fill', android: 'local_gas_station', web: 'local_gas_station' } },
  'ev-charging': { group: 'transportation', keywords: 'electric car battery', symbol: { ios: 'bolt.car.fill', android: 'electric_car', web: 'electric_car' } },
  parking: { group: 'transportation', keywords: 'car garage', symbol: { ios: 'parkingsign.circle.fill', android: 'local_parking', web: 'local_parking' } },
  toll: { group: 'transportation', keywords: 'peaje highway road', symbol: { ios: 'road.lanes', android: 'toll', web: 'toll' } },
  'car-service': { group: 'transportation', keywords: 'mechanic repair taller', symbol: { ios: 'wrench.adjustable.fill', android: 'car_repair', web: 'car_repair' } },
  motorcycle: { group: 'transportation', keywords: 'moto motocicleta', symbol: { ios: 'scooter', android: 'two_wheeler', web: 'two_wheeler' } },
  'car-wash': { group: 'transportation', keywords: 'lavadero lavado', symbol: { ios: 'bubbles.and.sparkles.fill', android: 'local_car_wash', web: 'local_car_wash' } },
  subway: { group: 'transportation', keywords: 'metro underground', symbol: { ios: 'tram.fill.tunnel', android: 'subway', web: 'subway' } },
  shuttle: { group: 'transportation', keywords: 'buseta van transfer airport', symbol: { ios: 'bus.doubledecker.fill', android: 'airport_shuttle', web: 'airport_shuttle' } },
  'e-scooter': { group: 'transportation', keywords: 'patineta scooter rental', symbol: { ios: 'bolt.circle.fill', android: 'electric_scooter', web: 'electric_scooter' } },
  fines: { group: 'transportation', keywords: 'multas comparendo tickets', symbol: { ios: 'exclamationmark.octagon.fill', android: 'local_police', web: 'local_police' } },
  'driving-license': { group: 'transportation', keywords: 'licencia pase documents', symbol: { ios: 'person.text.rectangle.fill', android: 'badge', web: 'badge' } },
  'road-trip': { group: 'transportation', keywords: 'carretera paseo route', symbol: { ios: 'signpost.right.fill', android: 'route', web: 'route' } },
  shopping: { group: 'shopping', keywords: 'bag purchases', symbol: { ios: 'bag.fill', android: 'shopping_bag', web: 'shopping_bag' } },
  cart: { group: 'shopping', keywords: 'store buy', symbol: { ios: 'cart.fill', android: 'shopping_cart', web: 'shopping_cart' } },
  clothing: { group: 'shopping', keywords: 'fashion apparel ropa', symbol: { ios: 'tshirt.fill', android: 'checkroom', web: 'checkroom' } },
  electronics: { group: 'shopping', keywords: 'computer tech gadgets', symbol: { ios: 'desktopcomputer', android: 'computer', web: 'computer' } },
  'online-shopping': { group: 'shopping', keywords: 'delivery parcel package envio', symbol: { ios: 'shippingbox.fill', android: 'inventory_2', web: 'inventory_2' } },
  mall: { group: 'shopping', keywords: 'centro comercial retail store', symbol: { ios: 'bag.circle.fill', android: 'local_mall', web: 'local_mall' } },
  jewelry: { group: 'shopping', keywords: 'watch accessories luxury', symbol: { ios: 'diamond.fill', android: 'diamond', web: 'diamond' } },
  watch: { group: 'shopping', keywords: 'reloj smartwatch', symbol: { ios: 'applewatch', android: 'watch', web: 'watch' } },
  'hardware-store': { group: 'shopping', keywords: 'ferreteria homecenter', symbol: { ios: 'wrench.and.screwdriver', android: 'hardware', web: 'hardware' } },
  'convenience-store': { group: 'shopping', keywords: 'tienda barrio minimarket', symbol: { ios: 'cart.circle.fill', android: 'local_convenience_store', web: 'local_convenience_store' } },
  market: { group: 'shopping', keywords: 'plaza mercado local', symbol: { ios: 'basket', android: 'storefront', web: 'storefront' } },
  'second-hand': { group: 'shopping', keywords: 'usado segunda mano thrift', symbol: { ios: 'arrow.3.trianglepath', android: 'recycling', web: 'recycling' } },
  headphones: { group: 'shopping', keywords: 'audifonos audio accessories', symbol: { ios: 'headphones', android: 'headphones', web: 'headphones' } },
  laptop: { group: 'shopping', keywords: 'portatil computer', symbol: { ios: 'laptopcomputer.and.iphone', android: 'laptop_mac', web: 'laptop_mac' } },
  devices: { group: 'shopping', keywords: 'dispositivos tablet celular', symbol: { ios: 'ipad.and.iphone', android: 'devices', web: 'devices' } },
  'sporting-goods': { group: 'shopping', keywords: 'deportes equipment', symbol: { ios: 'tennis.racket', android: 'sports_tennis', web: 'sports_tennis' } },
  health: { group: 'health', keywords: 'medical care salud', symbol: { ios: 'cross.case.fill', android: 'medical_services', web: 'medical_services' } },
  doctor: { group: 'health', keywords: 'clinic hospital consultation', symbol: { ios: 'stethoscope', android: 'local_hospital', web: 'local_hospital' } },
  pharmacy: { group: 'health', keywords: 'medicine prescription drugs', symbol: { ios: 'pills.fill', android: 'medication', web: 'medication' } },
  lab: { group: 'health', keywords: 'exams bloodwork analysis', symbol: { ios: 'cross.vial.fill', android: 'science', web: 'science' } },
  dental: { group: 'health', keywords: 'dentist teeth', symbol: { ios: 'mouth.fill', android: 'dentistry', web: 'dentistry' } },
  vision: { group: 'health', keywords: 'glasses optical eyes', symbol: { ios: 'eyeglasses', android: 'visibility', web: 'visibility' } },
  therapy: { group: 'health', keywords: 'mental health psychology counseling', symbol: { ios: 'brain.head.profile', android: 'psychology', web: 'psychology' } },
  fitness: { group: 'health', keywords: 'gym exercise weights', symbol: { ios: 'dumbbell.fill', android: 'fitness_center', web: 'fitness_center' } },
  hospital: { group: 'health', keywords: 'urgencias emergency clinica', symbol: { ios: 'cross.fill', android: 'emergency', web: 'emergency' } },
  physiotherapy: { group: 'health', keywords: 'fisioterapia rehab', symbol: { ios: 'figure.roll', android: 'accessible', web: 'accessible' } },
  'health-insurance': { group: 'health', keywords: 'eps prepagada medicina', symbol: { ios: 'heart.text.square.fill', android: 'health_and_safety', web: 'health_and_safety' } },
  'heart-health': { group: 'health', keywords: 'chequeo cardiology exam', symbol: { ios: 'waveform.path.ecg', android: 'monitor_heart', web: 'monitor_heart' } },
  hearing: { group: 'health', keywords: 'audiologia ears', symbol: { ios: 'ear.fill', android: 'hearing', web: 'hearing' } },
  supplements: { group: 'health', keywords: 'vitaminas suplementos', symbol: { ios: 'pills', android: 'medication_liquid', web: 'medication_liquid' } },
  yoga: { group: 'health', keywords: 'meditation pilates', symbol: { ios: 'figure.yoga', android: 'self_improvement', web: 'self_improvement' } },
  running: { group: 'health', keywords: 'correr trote marathon', symbol: { ios: 'figure.run', android: 'directions_run', web: 'directions_run' } },
  'martial-arts': { group: 'health', keywords: 'artes marciales karate boxing', symbol: { ios: 'figure.martial.arts', android: 'sports_martial_arts', web: 'sports_martial_arts' } },
  haircut: { group: 'personalCare', keywords: 'barber salon hair peluqueria', symbol: { ios: 'scissors', android: 'content_cut', web: 'content_cut' } },
  beauty: { group: 'personalCare', keywords: 'cosmetics makeup skincare', symbol: { ios: 'comb.fill', android: 'face', web: 'face' } },
  spa: { group: 'personalCare', keywords: 'massage relax yoga', symbol: { ios: 'figure.mind.and.body', android: 'spa', web: 'spa' } },
  laundry: { group: 'personalCare', keywords: 'dry cleaning washing lavanderia', symbol: { ios: 'washer.fill', android: 'local_laundry_service', web: 'local_laundry_service' } },
  hygiene: { group: 'personalCare', keywords: 'aseo personal soap', symbol: { ios: 'hands.sparkles.fill', android: 'soap', web: 'soap' } },
  shower: { group: 'personalCare', keywords: 'bano ducha shampoo', symbol: { ios: 'shower.fill', android: 'shower', web: 'shower' } },
  makeup: { group: 'personalCare', keywords: 'maquillaje cosmetics', symbol: { ios: 'paintbrush.pointed.fill', android: 'face_retouching_natural', web: 'face_retouching_natural' } },
  tailor: { group: 'personalCare', keywords: 'modista sastre arreglos', symbol: { ios: 'tshirt', android: 'dry_cleaning', web: 'dry_cleaning' } },
  education: { group: 'education', keywords: 'school study', symbol: { ios: 'graduationcap.fill', android: 'school', web: 'school' } },
  tuition: { group: 'education', keywords: 'university fees semester matricula', symbol: { ios: 'graduationcap.circle.fill', android: 'cast_for_education', web: 'cast_for_education' } },
  books: { group: 'education', keywords: 'reading library', symbol: { ios: 'books.vertical.fill', android: 'menu_book', web: 'menu_book' } },
  courses: { group: 'education', keywords: 'online training workshop', symbol: { ios: 'laptopcomputer', android: 'co_present', web: 'co_present' } },
  'school-supplies': { group: 'education', keywords: 'stationery backpack materials utiles', symbol: { ios: 'backpack.fill', android: 'backpack', web: 'backpack' } },
  languages: { group: 'education', keywords: 'idiomas ingles clases', symbol: { ios: 'character.book.closed.fill', android: 'translate', web: 'translate' } },
  'music-lessons': { group: 'education', keywords: 'clases musica piano', symbol: { ios: 'pianokeys', android: 'piano', web: 'piano' } },
  certification: { group: 'education', keywords: 'certificado exam diploma', symbol: { ios: 'checkmark.seal.fill', android: 'verified', web: 'verified' } },
  library: { group: 'education', keywords: 'biblioteca membership', symbol: { ios: 'books.vertical', android: 'local_library', web: 'local_library' } },
  stationery: { group: 'education', keywords: 'papeleria cuadernos notebooks', symbol: { ios: 'pencil.and.ruler.fill', android: 'edit_note', web: 'edit_note' } },
  scholarship: { group: 'education', keywords: 'beca grant award', symbol: { ios: 'rosette', android: 'military_tech', web: 'military_tech' } },
  entertainment: { group: 'entertainment', keywords: 'gaming fun console', symbol: { ios: 'gamecontroller.fill', android: 'sports_esports', web: 'sports_esports' } },
  movies: { group: 'entertainment', keywords: 'cinema film', symbol: { ios: 'film.fill', android: 'movie', web: 'movie' } },
  streaming: { group: 'entertainment', keywords: 'netflix spotify video', symbol: { ios: 'play.rectangle.fill', android: 'subscriptions', web: 'subscriptions' } },
  subscriptions: { group: 'entertainment', keywords: 'recurring membership renewal', symbol: { ios: 'arrow.triangle.2.circlepath', android: 'autorenew', web: 'autorenew' } },
  tv: { group: 'entertainment', keywords: 'television cable', symbol: { ios: 'tv.fill', android: 'tv', web: 'tv' } },
  music: { group: 'entertainment', keywords: 'audio songs', symbol: { ios: 'music.note', android: 'music_note', web: 'music_note' } },
  concerts: { group: 'entertainment', keywords: 'tickets events live boletas', symbol: { ios: 'ticket.fill', android: 'local_activity', web: 'local_activity' } },
  theater: { group: 'entertainment', keywords: 'arts show play teatro', symbol: { ios: 'theatermasks.fill', android: 'theater_comedy', web: 'theater_comedy' } },
  nightlife: { group: 'entertainment', keywords: 'club party dancing rumba', symbol: { ios: 'music.mic', android: 'nightlife', web: 'nightlife' } },
  hobbies: { group: 'entertainment', keywords: 'crafts art painting', symbol: { ios: 'paintpalette.fill', android: 'palette', web: 'palette' } },
  photography: { group: 'entertainment', keywords: 'camera photos', symbol: { ios: 'camera.fill', android: 'photo_camera', web: 'photo_camera' } },
  news: { group: 'entertainment', keywords: 'magazine press media', symbol: { ios: 'newspaper.fill', android: 'newspaper', web: 'newspaper' } },
  sports: { group: 'entertainment', keywords: 'ball recreation soccer', symbol: { ios: 'soccerball', android: 'sports_soccer', web: 'sports_soccer' } },
  'board-games': { group: 'entertainment', keywords: 'juegos de mesa dice', symbol: { ios: 'dice.fill', android: 'casino', web: 'casino' } },
  museum: { group: 'entertainment', keywords: 'museo exhibition culture', symbol: { ios: 'building.columns.circle', android: 'museum', web: 'museum' } },
  'amusement-park': { group: 'entertainment', keywords: 'parque diversiones rides', symbol: { ios: 'balloon.2.fill', android: 'attractions', web: 'attractions' } },
  podcasts: { group: 'entertainment', keywords: 'audio shows', symbol: { ios: 'mic.fill', android: 'podcasts', web: 'podcasts' } },
  apps: { group: 'entertainment', keywords: 'aplicaciones software licenses', symbol: { ios: 'app.badge.fill', android: 'apps', web: 'apps' } },
  'cloud-storage': { group: 'entertainment', keywords: 'nube icloud drive backup', symbol: { ios: 'icloud.fill', android: 'cloud', web: 'cloud' } },
  golf: { group: 'entertainment', keywords: 'club course', symbol: { ios: 'figure.golf', android: 'sports_golf', web: 'sports_golf' } },
  basketball: { group: 'entertainment', keywords: 'baloncesto', symbol: { ios: 'basketball.fill', android: 'sports_basketball', web: 'sports_basketball' } },
  fishing: { group: 'entertainment', keywords: 'pesca', symbol: { ios: 'fish', android: 'phishing', web: 'phishing' } },
  drawing: { group: 'entertainment', keywords: 'dibujo illustration art', symbol: { ios: 'pencil.tip', android: 'draw', web: 'draw' } },
  lottery: { group: 'entertainment', keywords: 'loteria chance apuestas betting', symbol: { ios: 'suit.club.fill', android: 'confirmation_number', web: 'confirmation_number' } },
  travel: { group: 'travel', keywords: 'trip vacation world viaje', symbol: { ios: 'globe.americas.fill', android: 'travel_explore', web: 'travel_explore' } },
  flight: { group: 'travel', keywords: 'plane airline airport', symbol: { ios: 'airplane', android: 'flight', web: 'flight' } },
  hotel: { group: 'travel', keywords: 'lodging stay accommodation', symbol: { ios: 'bed.double.fill', android: 'hotel', web: 'hotel' } },
  'car-rental': { group: 'travel', keywords: 'rent vehicle hire', symbol: { ios: 'car.rear.fill', android: 'car_rental', web: 'car_rental' } },
  luggage: { group: 'travel', keywords: 'suitcase baggage maleta', symbol: { ios: 'suitcase.fill', android: 'luggage', web: 'luggage' } },
  beach: { group: 'travel', keywords: 'sea resort summer playa', symbol: { ios: 'beach.umbrella.fill', android: 'beach_access', web: 'beach_access' } },
  camping: { group: 'travel', keywords: 'tent outdoors cabin', symbol: { ios: 'tent.fill', android: 'cabin', web: 'cabin' } },
  hiking: { group: 'travel', keywords: 'trekking mountain trail', symbol: { ios: 'figure.hiking', android: 'hiking', web: 'hiking' } },
  sightseeing: { group: 'travel', keywords: 'tour map attractions', symbol: { ios: 'map.fill', android: 'map', web: 'map' } },
  visa: { group: 'travel', keywords: 'pasaporte documentos embassy', symbol: { ios: 'airplane.circle.fill', android: 'airplane_ticket', web: 'airplane_ticket' } },
  cruise: { group: 'travel', keywords: 'crucero ship', symbol: { ios: 'ferry', android: 'directions_boat_filled', web: 'directions_boat_filled' } },
  'vacation-rental': { group: 'travel', keywords: 'airbnb finca cabana', symbol: { ios: 'house.lodge.fill', android: 'cottage', web: 'cottage' } },
  mountains: { group: 'travel', keywords: 'montana nature landscape', symbol: { ios: 'mountain.2.fill', android: 'landscape', web: 'landscape' } },
  ski: { group: 'travel', keywords: 'snow esqui winter', symbol: { ios: 'figure.skiing.downhill', android: 'downhill_skiing', web: 'downhill_skiing' } },
  bank: { group: 'finance', keywords: 'financial institution banco', symbol: { ios: 'building.columns.fill', android: 'account_balance', web: 'account_balance' } },
  'credit-card': { group: 'finance', keywords: 'payment debt tarjeta', symbol: { ios: 'creditcard.fill', android: 'credit_card', web: 'credit_card' } },
  savings: { group: 'finance', keywords: 'piggy bank money ahorro', symbol: { ios: 'banknote.fill', android: 'savings', web: 'savings' } },
  investment: { group: 'finance', keywords: 'stocks growth chart', symbol: { ios: 'chart.line.uptrend.xyaxis', android: 'trending_up', web: 'trending_up' } },
  crypto: { group: 'finance', keywords: 'bitcoin blockchain digital', symbol: { ios: 'bitcoinsign.circle.fill', android: 'currency_bitcoin', web: 'currency_bitcoin' } },
  dividends: { group: 'finance', keywords: 'yield returns payout', symbol: { ios: 'chart.pie.fill', android: 'pie_chart', web: 'pie_chart' } },
  loan: { group: 'finance', keywords: 'credit borrow installment prestamo', symbol: { ios: 'building.columns.circle.fill', android: 'request_quote', web: 'request_quote' } },
  fees: { group: 'finance', keywords: 'charges commission interest', symbol: { ios: 'percent', android: 'percent', web: 'percent' } },
  taxes: { group: 'finance', keywords: 'impuestos government declaration', symbol: { ios: 'doc.plaintext.fill', android: 'description', web: 'description' } },
  insurance: { group: 'finance', keywords: 'coverage policy seguro', symbol: { ios: 'umbrella.fill', android: 'umbrella', web: 'umbrella' } },
  atm: { group: 'finance', keywords: 'withdrawal efectivo cajero', symbol: { ios: 'dollarsign.circle.fill', android: 'local_atm', web: 'local_atm' } },
  wallet: { group: 'finance', keywords: 'cash pocket money billetera', symbol: { ios: 'wallet.pass.fill', android: 'wallet', web: 'wallet' } },
  exchange: { group: 'finance', keywords: 'currency conversion swap fx', symbol: { ios: 'arrow.left.arrow.right', android: 'swap_horiz', web: 'swap_horiz' } },
  refund: { group: 'finance', keywords: 'return reimbursement devolucion', symbol: { ios: 'arrow.uturn.backward.circle.fill', android: 'currency_exchange', web: 'currency_exchange' } },
  'emergency-fund': { group: 'finance', keywords: 'fondo emergencia reserve', symbol: { ios: 'shield.fill', android: 'shield', web: 'shield' } },
  'debt-payment': { group: 'finance', keywords: 'deuda abono cuota', symbol: { ios: 'minus.circle.fill', android: 'money_off', web: 'money_off' } },
  budget: { group: 'finance', keywords: 'presupuesto plan', symbol: { ios: 'chart.pie', android: 'account_balance_wallet', web: 'account_balance_wallet' } },
  cash: { group: 'finance', keywords: 'efectivo billetes coins', symbol: { ios: 'dollarsign.square.fill', android: 'paid', web: 'paid' } },
  'stock-market': { group: 'finance', keywords: 'bolsa acciones trading', symbol: { ios: 'chart.bar.xaxis', android: 'candlestick_chart', web: 'candlestick_chart' } },
  accounting: { group: 'finance', keywords: 'contador contabilidad calculator', symbol: { ios: 'plus.forwardslash.minus', android: 'calculate', web: 'calculate' } },
  legal: { group: 'finance', keywords: 'abogado notaria lawyer', symbol: { ios: 'doc.text.magnifyingglass', android: 'gavel', web: 'gavel' } },
  'credit-score': { group: 'finance', keywords: 'datacredito historial rating', symbol: { ios: 'gauge', android: 'speed', web: 'speed' } },
  salary: { group: 'work', keywords: 'paycheck wages nomina', symbol: { ios: 'banknote.fill', android: 'payments', web: 'payments' } },
  freelance: { group: 'work', keywords: 'work contract client', symbol: { ios: 'briefcase.fill', android: 'work', web: 'work' } },
  business: { group: 'work', keywords: 'company revenue sales', symbol: { ios: 'chart.bar.fill', android: 'bar_chart', web: 'bar_chart' } },
  office: { group: 'work', keywords: 'workplace coworking desk', symbol: { ios: 'building.fill', android: 'business_center', web: 'business_center' } },
  bonus: { group: 'work', keywords: 'income award prima', symbol: { ios: 'star.circle.fill', android: 'workspace_premium', web: 'workspace_premium' } },
  tips: { group: 'work', keywords: 'gratuity propina extra', symbol: { ios: 'star.fill', android: 'star', web: 'star' } },
  'rental-income': { group: 'work', keywords: 'arriendo tenant property', symbol: { ios: 'key.fill', android: 'key', web: 'key' } },
  pension: { group: 'work', keywords: 'retirement jubilacion', symbol: { ios: 'hourglass', android: 'hourglass_empty', web: 'hourglass_empty' } },
  commission: { group: 'work', keywords: 'comision ventas deal', symbol: { ios: 'arrow.left.arrow.right.circle.fill', android: 'handshake', web: 'handshake' } },
  consulting: { group: 'work', keywords: 'consultoria asesoria services', symbol: { ios: 'person.crop.circle.badge.checkmark', android: 'support_agent', web: 'support_agent' } },
  royalties: { group: 'work', keywords: 'regalias licensing copyright', symbol: { ios: 'c.circle.fill', android: 'copyright', web: 'copyright' } },
  selling: { group: 'work', keywords: 'venta marketplace resale', symbol: { ios: 'tag.circle.fill', android: 'local_offer', web: 'local_offer' } },
  cashback: { group: 'work', keywords: 'puntos rewards reembolso', symbol: { ios: 'giftcard.fill', android: 'card_giftcard', web: 'card_giftcard' } },
  'remote-work': { group: 'work', keywords: 'teletrabajo home office', symbol: { ios: 'house.and.flag', android: 'home_work', web: 'home_work' } },
  family: { group: 'family', keywords: 'people household familia', symbol: { ios: 'person.3.fill', android: 'family_restroom', web: 'family_restroom' } },
  friends: { group: 'family', keywords: 'social group people amigos', symbol: { ios: 'person.2.fill', android: 'group', web: 'group' } },
  childcare: { group: 'family', keywords: 'children daycare nanny', symbol: { ios: 'figure.and.child.holdinghands', android: 'child_care', web: 'child_care' } },
  baby: { group: 'family', keywords: 'newborn stroller diapers bebe', symbol: { ios: 'stroller.fill', android: 'stroller', web: 'stroller' } },
  toys: { group: 'family', keywords: 'kids play juguetes', symbol: { ios: 'teddybear.fill', android: 'toys', web: 'toys' } },
  pets: { group: 'family', keywords: 'dog cat animal mascota', symbol: { ios: 'pawprint.fill', android: 'pets', web: 'pets' } },
  vet: { group: 'family', keywords: 'veterinary animal health', symbol: { ios: 'syringe.fill', android: 'vaccines', web: 'vaccines' } },
  gift: { group: 'family', keywords: 'present regalo', symbol: { ios: 'gift.fill', android: 'redeem', web: 'redeem' } },
  celebration: { group: 'family', keywords: 'party birthday fiesta', symbol: { ios: 'party.popper.fill', android: 'celebration', web: 'celebration' } },
  wedding: { group: 'family', keywords: 'marriage anniversary matrimonio', symbol: { ios: 'heart.circle.fill', android: 'favorite', web: 'favorite' } },
  'elderly-care': { group: 'family', keywords: 'adulto mayor abuelos parents', symbol: { ios: 'figure.walk', android: 'elderly', web: 'elderly' } },
  'kids-activities': { group: 'family', keywords: 'actividades ninos extracurricular', symbol: { ios: 'figure.and.child.holdinghands', android: 'sports_handball', web: 'sports_handball' } },
  birthday: { group: 'family', keywords: 'cumpleanos cake', symbol: { ios: 'birthday.cake', android: 'cake', web: 'cake' } },
  holidays: { group: 'family', keywords: 'navidad christmas fiestas', symbol: { ios: 'gift.circle.fill', android: 'festival', web: 'festival' } },
  religious: { group: 'family', keywords: 'iglesia diezmo tithe church', symbol: { ios: 'heart.circle', android: 'church', web: 'church' } },
  charity: { group: 'other', keywords: 'donation giving donacion', symbol: { ios: 'heart.fill', android: 'volunteer_activism', web: 'volunteer_activism' } },
  tag: { group: 'other', keywords: 'label custom generic', symbol: { ios: 'tag.fill', android: 'sell', web: 'sell' } },
  uncategorized: { group: 'other', keywords: 'unknown pending question', symbol: { ios: 'questionmark.circle.fill', android: 'help', web: 'help' } },
  other: { group: 'other', keywords: 'miscellaneous category', symbol: { ios: 'square.grid.2x2.fill', android: 'category', web: 'category' } },
  personal: { group: 'other', keywords: 'yo gastos personales', symbol: { ios: 'person.fill', android: 'person', web: 'person' } },
  emergency: { group: 'other', keywords: 'imprevisto urgente unexpected', symbol: { ios: 'exclamationmark.triangle.fill', android: 'warning', web: 'warning' } },
  favorite: { group: 'other', keywords: 'bookmark saved', symbol: { ios: 'bookmark.fill', android: 'bookmark', web: 'bookmark' } },
  flag: { group: 'other', keywords: 'marker goal meta', symbol: { ios: 'flag.fill', android: 'flag', web: 'flag' } },
  private: { group: 'other', keywords: 'privado lock secret', symbol: { ios: 'lock.fill', android: 'lock', web: 'lock' } },
  annual: { group: 'other', keywords: 'anual yearly calendar', symbol: { ios: 'calendar', android: 'calendar_month', web: 'calendar_month' } },
  installments: { group: 'other', keywords: 'cuotas plazos schedule', symbol: { ios: 'clock.fill', android: 'schedule', web: 'schedule' } },
  alerts: { group: 'other', keywords: 'recordatorio notification', symbol: { ios: 'bell.fill', android: 'notifications', web: 'notifications' } },
  location: { group: 'other', keywords: 'lugar ubicacion place', symbol: { ios: 'mappin.circle.fill', android: 'location_on', web: 'location_on' } },
} satisfies Record<string, CategoryIconDefinition>;

export type CategoryIcon = keyof typeof categoryIconCatalog;
export const categoryIconKeys = Object.keys(categoryIconCatalog) as CategoryIcon[];
export const fallbackCategoryIcon: CategoryIcon = 'other';
export function isCategoryIcon(value: string): value is CategoryIcon { return Object.prototype.hasOwnProperty.call(categoryIconCatalog, value); }
export function getCategoryIcon(value: string): SymbolViewProps['name'] { return isCategoryIcon(value) ? categoryIconCatalog[value].symbol : categoryIconCatalog[fallbackCategoryIcon].symbol; }

/**
 * Icons matching a query, in catalog order. Matches the key, the English label,
 * group and keywords — so English and Spanish keywords work in every language —
 * plus the label and group in `language` (the active one by default). Case and
 * accents are ignored.
 */
export function searchCategoryIcons(query: string, language: Language = getLanguage()): CategoryIcon[] {
  const needle = foldForSearch(query);
  if (!needle) return [...categoryIconKeys];
  const english = getMessagesFor('en').categories;
  const active = getMessagesFor(language).categories;
  return categoryIconKeys.filter((id) => {
    const item = categoryIconCatalog[id];
    const haystack = `${id} ${english.icons[id]} ${english.iconGroups[item.group]} ${item.keywords} ${active.icons[id]} ${active.iconGroups[item.group]}`;
    return foldForSearch(haystack).includes(needle);
  });
}
