import { and, desc, eq, gte, lt, sql } from 'drizzle-orm';
import { database } from '@/database/client';
import { accounts, categories, transactions } from '@/database/schema';
import type { TransactionRepository } from './transaction.repository';
import type { MonthlyTransactionSummary, SupportedTransactionType, TransactionListItem, TransactionRecord } from './transaction.types';

const selection = { transaction: transactions, accountName: accounts.name, categoryName: categories.name, categoryIcon: categories.icon };
function mapRow(row: { transaction: typeof transactions.$inferSelect; accountName: string; categoryName: string; categoryIcon: string | null }): TransactionListItem { return { ...row.transaction, type: row.transaction.type as SupportedTransactionType, status: row.transaction.status as 'posted' | 'voided', destinationAccountId: null, accountId: row.transaction.accountId!, categoryId: row.transaction.categoryId!, note: row.transaction.note, currency: 'COP', accountName: row.accountName, categoryName: row.categoryName, categoryIcon: row.categoryIcon ?? 'other' }; }
export class SQLiteTransactionRepository implements TransactionRepository {
  async create(transaction: TransactionRecord): Promise<void> { await database.insert(transactions).values(transaction); }
  async list(): Promise<TransactionListItem[]> { const rows = await database.select(selection).from(transactions).innerJoin(accounts, eq(transactions.accountId, accounts.id)).innerJoin(categories, eq(transactions.categoryId, categories.id)).where(sql`${transactions.type} IN ('expense', 'income')`).orderBy(desc(transactions.transactionDate), desc(transactions.createdAt)); return rows.map(mapRow); }
  async recent(limit: number): Promise<TransactionListItem[]> { const rows = await database.select(selection).from(transactions).innerJoin(accounts, eq(transactions.accountId, accounts.id)).innerJoin(categories, eq(transactions.categoryId, categories.id)).where(and(eq(transactions.status, 'posted'), sql`${transactions.type} IN ('expense', 'income')`)).orderBy(desc(transactions.transactionDate), desc(transactions.createdAt)).limit(limit); return rows.map(mapRow); }
  async summarizeMonth(month: string): Promise<MonthlyTransactionSummary> { const start = `${month}-01`; const [year, monthNumber] = month.split('-').map(Number); const next = monthNumber === 12 ? `${year + 1}-01-01` : `${year}-${String(monthNumber + 1).padStart(2, '0')}-01`; const [row] = await database.select({ income: sql<number>`coalesce(sum(case when ${transactions.type} = 'income' then ${transactions.amount} else 0 end), 0)`, expenses: sql<number>`coalesce(sum(case when ${transactions.type} = 'expense' then ${transactions.amount} else 0 end), 0)` }).from(transactions).where(and(eq(transactions.status, 'posted'), gte(transactions.transactionDate, start), lt(transactions.transactionDate, next))); const income = Number(row.income); const expenses = Number(row.expenses); return { income, expenses, net: income - expenses }; }
}
